const en = {
  title: 'My Rewards',
  subtitle: 'Redeem your civic contribution points for transit passes and city services.',
  balanceLabel: 'Total Balance',
  ptsLabel: 'pts',
  monthLabel: 'This Month',
  tierLabel: 'Tier Level',
  qrTitle: 'Active Transit Pass',
  qrSubtitle: 'Scan at gate for entry',
  expiresLabel: 'Expires',
  fareTypeLabel: 'Fare Type',
  reportsTitle: 'Recent Activity',
  viewAllBtn: 'View All',
  worksReportTitle: 'Report Issues',
  worksReportDesc: 'Document civic needs and earn immediate points upon verification.',
  worksTransitTitle: 'Redeem Transit',
  worksTransitDesc: 'Convert points into digital bus, metro, or ferry passes instantly.',
  worksLevelTitle: 'Level Up',
  worksLevelDesc: 'Higher tiers unlock faster rewards and exclusive city events.',
  storeTitle: 'Redeem Points Store',
  pass200Title: 'Metro Single Ride Pass',
  pass200Desc: '200 points • Valid on all routes for 2 hours.',
  pass500Title: 'Bus Day Pass',
  pass500Desc: '500 points • Unlimited rides for 24 hours.',
  redeemSuccess: 'Pass redeemed successfully! Checked in Wallet.',
  redeemFail: 'Insufficient points balance!'
};

export const WALLET_STRINGS: Record<string, typeof en> = {
  en,
  hi: {
    title: 'मेरे पुरस्कार',
    subtitle: 'पारगमन पास और शहर सेवाओं के लिए अपने नागरिक योगदान अंकों को भुनाएं।',
    balanceLabel: 'कुल शेष राशि',
    ptsLabel: 'अंक',
    monthLabel: 'इस महीने',
    tierLabel: 'टियर स्तर',
    qrTitle: 'सक्रिय पारगमन पास',
    qrSubtitle: 'प्रवेश के लिए गेट पर स्कैन करें',
    expiresLabel: 'समाप्ति तिथि',
    fareTypeLabel: 'किराया प्रकार',
    reportsTitle: 'हाल की गतिविधि',
    viewAllBtn: 'सभी देखें',
    worksReportTitle: 'मुद्दों की रिपोर्ट करें',
    worksReportDesc: 'नागरिक आवश्यकताओं को दस्तावेज करें और सत्यापन पर तत्काल अंक अर्जित करें।',
    worksTransitTitle: 'पारगमन भुनाएं',
    worksTransitDesc: 'अंकों को तुरंत डिजिटल बस, मेट्रो या फेरी पास में बदलें।',
    worksLevelTitle: 'स्तर बढ़ाएं',
    worksLevelDesc: 'उच्च टियर तेज़ पुरस्कार और विशेष शहर कार्यक्रमों को अनलॉक करते हैं।',
    storeTitle: 'अंक भुनाने का स्टोर',
    pass200Title: 'मेट्रो सिंगल राइड पास',
    pass200Desc: '200 अंक • 2 घंटे के लिए सभी मार्गों पर मान्य।',
    pass500Title: 'बस डे पास',
    pass500Desc: '500 अंक • 24 घंटे के लिए असीमित सवारी।',
    redeemSuccess: 'पास सफलतापूर्वक भुनाया गया! वॉलेट में चेक करें।',
    redeemFail: 'अपर्याप्त अंक शेष राशि!'
  },
  kn: {
    title: 'ನನ್ನ ಬಹುಮಾನಗಳು',
    subtitle: 'ಸಾರಿಗೆ ಪಾಸ್‌ಗಳು ಮತ್ತು ನಗರ ಸೇವೆಗಳಿಗಾಗಿ ನಿಮ್ಮ ನಾಗರಿಕ ಕೊಡುಗೆ ಅಂಕಗಳನ್ನು ಪಡೆದುಕೊಳ್ಳಿ.',
    balanceLabel: 'ಒಟ್ಟು ಬಾಕಿ',
    ptsLabel: 'ಅಂಕಗಳು',
    monthLabel: 'ಈ ತಿಂಗಳು',
    tierLabel: 'ಶ್ರೇಣಿ ಮಟ್ಟ',
    qrTitle: 'ಸಕ್ರಿಯ ಸಾರಿಗೆ ಪಾಸ್',
    qrSubtitle: 'ಪ್ರವೇಶಕ್ಕಾಗಿ ಗೇಟ್‌ನಲ್ಲಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    expiresLabel: 'ಅವಧಿ ಮುಗಿಯುವುದು',
    fareTypeLabel: 'ದರ ಪ್ರಕಾರ',
    reportsTitle: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    viewAllBtn: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    worksReportTitle: 'ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ',
    worksReportDesc: 'ನಾಗರಿಕ ಅಗತ್ಯಗಳನ್ನು ದಾಖಲಿಸಿ ಮತ್ತು ಪರಿಶೀಲನೆಯ ನಂತರ ತಕ್ಷಣದ ಅಂಕಗಳನ್ನು ಗಳಿಸಿ.',
    worksTransitTitle: 'ಸಾರಿಗೆ ಪಡೆದುಕೊಳ್ಳಿ',
    worksTransitDesc: 'ಅಂಕಗಳನ್ನು ತಕ್ಷಣವೇ ಡಿಜಿಟಲ್ ಬಸ್, ಮೆಟ್ರೋ ಅಥವಾ ದೋಣಿ ಪಾಸ್‌ಗಳಾಗಿ ಪರಿವರ್ತಿಸಿ.',
    worksLevelTitle: 'ಮಟ್ಟ ಹೆಚ್ಚಿಸಿ',
    worksLevelDesc: 'ಉನ್ನತ ಶ್ರೇಣಿಗಳು ವೇಗದ ಬಹುಮಾನಗಳು ಮತ್ತು ವಿಶೇಷ ನಗರ ಈವೆಂಟ್‌ಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡುತ್ತವೆ.',
    storeTitle: 'ಅಂಕಗಳನ್ನು ಬಳಸುವ ಸ್ಟೋರ್',
    pass200Title: 'ಮೆಟ್ರೋ ಸಿಂಗಲ್ ರೈಡ್ ಪಾಸ್',
    pass200Desc: '200 ಅಂಕಗಳು • 2 ಗಂಟೆಗಳ ಕಾಲ ಎಲ್ಲಾ ಮಾರ್ಗಗಳಲ್ಲಿ ಮಾನ್ಯವಾಗಿರುತ್ತದೆ.',
    pass500Title: 'ಬಸ್ ಡೇ ಪಾಸ್',
    pass500Desc: '500 ಅಂಕಗಳು • 24 ಗಂಟೆಗಳ ಕಾಲ ಅನಿಯಮಿತ ಪ್ರಯಾಣ.',
    redeemSuccess: 'ಪಾಸ್ ಯಶಸ್ವಿಯಾಗಿ ಪಡೆದುಕೊಳ್ಳಲಾಗಿದೆ! ವಾಲೆಟ್ ಪರಿಶೀಲಿಸಿ.',
    redeemFail: 'ಅಪರ್ಯಾಪ್ತ ಅಂಕಗಳ ಬಾಕಿ!'
  },
  bn: {
    title: 'আমার পুরস্কার',
    subtitle: 'পরিবহন পাস এবং শহরের পরিষেবার জন্য আপনার নাগরিক অবদানের পয়েন্টগুলি ভাঙিয়ে নিন।',
    balanceLabel: 'মোট ব্যালেন্স',
    ptsLabel: 'পয়েন্ট',
    monthLabel: 'এই মাসে',
    tierLabel: 'টিয়ার স্তর',
    qrTitle: 'সক্রিয় পরিবহন পাস',
    qrSubtitle: 'প্রবেশের জন্য গেটে স্ক্যান করুন',
    expiresLabel: 'মেয়াদ শেষ',
    fareTypeLabel: 'ভাড়ার ধরণ',
    reportsTitle: 'সাম্প্রতিক কার্যকলাপ',
    viewAllBtn: 'সব দেখুন',
    worksReportTitle: 'সমস্যা রিপোর্ট করুন',
    worksReportDesc: 'নাগরিক চাহিদা নথিভুক্ত করুন এবং যাচাইকরণের পর তাৎক্ষণিক পয়েন্ট অর্জন করুন।',
    worksTransitTitle: 'পয়েন্ট ভাঙান',
    worksTransitDesc: 'পয়েন্টগুলি অবিলম্বে ডিজিটাল বাস, মেট্রো বা ফেরি পাসে রূপান্তর করুন।',
    worksLevelTitle: 'লেভেল আপ করুন',
    worksLevelDesc: 'উচ্চতর স্তরগুলি দ্রুত পুরস্কার এবং বিশেষ শহরের ইভেন্ট আনলক করে।',
    storeTitle: 'পয়েন্ট রিডিম স্টোর',
    pass200Title: 'মেট্রো একক যাত্রা পাস',
    pass200Desc: '২০০ পয়েন্ট • ২ ঘণ্টার জন্য সব রুটে বৈধ।',
    pass500Title: 'বাস ডে পাস',
    pass500Desc: '৫০০ পয়েন্ট • ২৪ ঘণ্টার জন্য আনলিমিটেড যাত্রা।',
    redeemSuccess: 'পাস সফলভাবে রিডিম করা হয়েছে! ওয়ালেটে চেক করুন।',
    redeemFail: 'অপ্রতুল পয়েন্ট ব্যালেন্স!'
  },
  ta: {
    title: 'எனது பரிசுகள்',
    subtitle: 'போக்குவரத்து பாஸ்கள் மற்றும் நகர சேவைகளுக்காக உங்கள் பங்களிப்பு புள்ளிகளைப் பயன்படுத்திக் கொள்ளுங்கள்.',
    balanceLabel: 'மொத்த இருப்பு',
    ptsLabel: 'புள்ளிகள்',
    monthLabel: 'இந்த மாதம்',
    tierLabel: 'அடுக்கு நிலை',
    qrTitle: 'செயலில் உள்ள போக்குவரத்து பாஸ்',
    qrSubtitle: 'நுழைவிற்காக கேட்டில் ஸ்கேன் செய்யவும்',
    expiresLabel: 'காலாவதி',
    fareTypeLabel: 'கட்டண வகை',
    reportsTitle: 'சமீபத்திய நடவடிக்கை',
    viewAllBtn: 'அனைத்தையும் காட்டு',
    worksReportTitle: 'பிரச்சினைகளைப் புகாரளி',
    worksReportDesc: 'குடிமைத் தேவைகளை ஆவணப்படுத்தி, சரிபார்த்தவுடன் உடனடிப் புள்ளிகளைப் பெறுங்கள்.',
    worksTransitTitle: 'போக்குவரத்து பாஸ் பெறுங்கள்',
    worksTransitDesc: 'புள்ளிகளை உடனடியாக டிஜிட்டல் பேருந்து, மெட்ரோ அல்லது படகு பாஸ்களாக மாற்றவும்.',
    worksLevelTitle: 'அடுத்த நிலைக்குச் செல்லுங்கள்',
    worksLevelDesc: 'உயர்ந்த அடுக்குகள் வேகமான வெகுமதிகளையும் பிரத்யேக நகர நிகழ்வுகளையும் திறக்கின்றன.',
    storeTitle: 'புள்ளிகளைப் பயன்படுத்தும் ஸ்டோர்',
    pass200Title: 'மெட்ரோ ஒற்றை வழிப் பயணம்',
    pass200Desc: '200 புள்ளிகள் • 2 மணிநேரத்திற்கு அனைத்து வழிகளிலும் செல்லும்.',
    pass500Title: 'பேருந்து நாள் பாஸ்',
    pass500Desc: '500 புள்ளிகள் • 24 மணிநேரத்திற்கு வரம்பற்ற பயணம்.',
    redeemSuccess: 'பாஸ் வெற்றிகரமாகப் பெறப்பட்டது! வாலட்டில் சரிபார்க்கவும்.',
    redeemFail: 'போதிய புள்ளிகள் இருப்பு இல்லை!'
  },
  te: {
    title: 'నా రివార్డులు',
    subtitle: 'రవాణా పాస్‌లు మరియు నగర సేవల కోసం మీ పౌర సహకార పాయింట్లను రీడీమ్ చేయండి.',
    balanceLabel: 'మొత్తం బ్యాలెన్స్',
    ptsLabel: 'పాయింట్లు',
    monthLabel: 'ఈ నెల',
    tierLabel: 'టైర్ స్థాయి',
    qrTitle: 'క్రియాశీల రవాణా పాస్',
    qrSubtitle: 'ప్రవేశం కోసం గేట్ వద్ద స్కాన్ చేయండి',
    expiresLabel: 'గడువు ముగింపు',
    fareTypeLabel: 'ఛార్జీ రకం',
    reportsTitle: 'ఇటీవలి కార్యాచరణ',
    viewAllBtn: 'అన్నీ వీక్షించండి',
    worksReportTitle: 'సమస్యలను నివేదించండి',
    worksReportDesc: 'పౌర అవసరాలను డాక్యుమెంట్ చేయండి మరియు ధృవీకరణ తర్వాత తక్షణ పాయింట్లను పొందండి.',
    worksTransitTitle: 'రవాణా రీడీమ్',
    worksTransitDesc: 'పాయింట్లను తక్షణమే డిజిటల్ బస్సు, మెట్రో లేదా ఫెర్రీ పాస్‌లుగా మార్చండి.',
    worksLevelTitle: 'స్థాయిని పెంచుకోండి',
    worksLevelDesc: 'అధిక టైర్లు వేగవంతమైన రివార్డ్‌లు మరియు ప్రత్యేక నగర ఈవెంట్‌లను అన్‌లాక్ చేస్తాయి.',
    storeTitle: 'పాయింట్ల స్టోర్',
    pass200Title: 'మెట్రో సింగిల్ రైడ్ పాస్',
    pass200Desc: '200 పాయింట్లు • 2 గంటల పాటు అన్ని మార్గాల్లో చెల్లుతుంది.',
    pass500Title: 'బస్సు డే పాస్',
    pass500Desc: '500 పాయింట్లు • 24 గంటల పాటు అపరిమిత ప్రయాణాలు.',
    redeemSuccess: 'పాస్ విజయవంతంగా రీడీమ్ చేయబడింది! వాలెట్‌లో తనిఖీ చేయండి.',
    redeemFail: 'సరిపోని పాయింట్ల బ్యాలెన్స్!'
  },
  mr: {
    title: 'माझे पुरस्कार',
    subtitle: 'वाहतूक पास आणि शहर सेवांसाठी तुमचे नागरी योगदान गुण मिळवा.',
    balanceLabel: 'एकूण शिल्लक',
    ptsLabel: 'गुण',
    monthLabel: 'या महिन्यात',
    tierLabel: 'टियर पातळी',
    qrTitle: 'सक्रिय वाहतूक पास',
    qrSubtitle: 'प्रवेशासाठी गेटवर स्कॅन करा',
    expiresLabel: 'समाप्ती',
    fareTypeLabel: 'भाडे प्रकार',
    reportsTitle: 'अलीकडील क्रियाकलाप',
    viewAllBtn: 'सर्व पहा',
    worksReportTitle: 'समस्या नोंदवा',
    worksReportDesc: 'नागरी गरजा दस्तऐवजीकरण करा आणि पडताळणीनंतर त्वरित गुण मिळवा.',
    worksTransitTitle: 'पास खरेदी करा',
    worksTransitDesc: 'गुणांचे त्वरित डिजिटल बस, मेट्रो किंवा फेरी पासमध्ये रूपांतर करा.',
    worksLevelTitle: 'पातळी वाढवा',
    worksLevelDesc: 'उच्च स्तर जलद बक्षिसे आणि विशेष शहर कार्यक्रम अनलॉक करतात.',
    storeTitle: 'गुण वापरण्याचे स्टोअर',
    pass200Title: 'मेट्रो सिंगल राइड पास',
    pass200Desc: '२०० गुण • २ तासांसाठी सर्व मार्गांवर वैध.',
    pass500Title: 'बस डे पास',
    pass500Desc: '५०० गुण • २४ तासांसाठी अमर्यादित प्रवास.',
    redeemSuccess: 'पास यशस्वीरित्या खरेदी केला! वॉलेटमध्ये तपासा.',
    redeemFail: 'अपुरे गुण शिल्लक!'
  },
  ur: {
    title: 'میرے انعامات',
    subtitle: 'بلدیاتی خدمات اور سفری ٹکٹوں کے لیے اپنے پوائنٹس کا استعمال کریں۔',
    balanceLabel: 'کل بیلنس',
    ptsLabel: 'پوائنٹس',
    monthLabel: 'اس مہینے',
    tierLabel: 'درجہ',
    qrTitle: 'فعال سفری پاس',
    qrSubtitle: 'داخلی دروازے پر اسکین کریں',
    expiresLabel: 'میعاد',
    fareTypeLabel: 'ٹکٹ کی قسم',
    reportsTitle: 'حالیہ سرگرمی',
    viewAllBtn: 'سب دیکھیں',
    worksReportTitle: 'مسائل رپورٹ کریں',
    worksReportDesc: 'شہری ضروریات کی رپورٹ کریں اور پوائنٹس حاصل کریں۔',
    worksTransitTitle: 'ٹکٹ حاصل کریں',
    worksTransitDesc: 'اپنے پوائنٹس کو بس یا میٹرو پاس میں تبدیل کریں۔',
    worksLevelTitle: 'اپ گریڈ کریں',
    worksLevelDesc: 'اعلیٰ درجے سے مزید انعامات حاصل کریں۔',
    storeTitle: 'پوائنٹس اسٹور',
    pass200Title: 'میٹرو سنگل رائیڈ پاس',
    pass200Desc: '200 پوائنٹس • 2 گھنٹے کے لیے تمام راستوں پر کارآمد۔',
    pass500Title: 'بس ڈے پاس',
    pass500Desc: '500 پوائنٹس • 24 گھنٹے کے لیے لامحدود سفر۔',
    redeemSuccess: 'کامیابی سے حاصل کر لیا گیا! والٹ چیک کریں۔',
    redeemFail: 'ناکافی پوائنٹس بیلنس!'
  },
  gu: {
    title: 'મારા પુરસ્કારો',
    subtitle: 'પરિવહન પાસ અને શહેર સેવાઓ માટે તમારા નાગરિક યોગદાન પોઇન્ટ્સ વાપરો.',
    balanceLabel: 'કુલ સિલક',
    ptsLabel: 'પોઇન્ટ્સ',
    monthLabel: 'આ મહિને',
    tierLabel: 'ટિયર લેવલ',
    qrTitle: 'સક્રિય પરિવહન પાસ',
    qrSubtitle: 'પ્રવેશ માટે ગેટ પર સ્કેન કરો',
    expiresLabel: 'સમાપ્તિ',
    fareTypeLabel: 'ભાડાનો પ્રકાર',
    reportsTitle: 'તાજેતરની પ્રવૃત્તિ',
    viewAllBtn: 'બધા જુઓ',
    worksReportTitle: 'સમસ્યા રિપોર્ટ કરો',
    worksReportDesc: 'નાગરિક જરૂરિયાતો દસ્તાવેજ કરો અને ચકાસણી પર તાત્કાલિક પોઇન્ટ મેળવો.',
    worksTransitTitle: 'પાસ મેળવો',
    worksTransitDesc: 'પોઇન્ટ્સને તરત જ ડિજિટલ બસ, મેટ્રો અથવા ફેરી પાસમાં રૂપાંતરિત કરો.',
    worksLevelTitle: 'લેવલ અપ કરો',
    worksLevelDesc: 'ઉચ્ચ સ્તર ઝડપી પુરસ્કારો અને વિશેષ શહેર ઇવેન્ટ્સ અનલોક કરે છે.',
    storeTitle: 'પોઇન્ટ્સ રીડીમ સ્ટોર',
    pass200Title: 'મેટ્રો સિંગલ રાઇડ પાસ',
    pass200Desc: '200 પોઇન્ટ્સ • 2 કલાક માટે તમામ રૂટ પર માન્ય.',
    pass500Title: 'બસ ડે પાસ',
    pass500Desc: '500 પોઇન્ટ્સ • 24 કલાક માટે અમર્યાદિત સવારી.',
    redeemSuccess: 'પાસ સફળતાપૂર્વક મેળવ્યો! વોલેટમાં તપાસો.',
    redeemFail: 'અપૂરતા પોઇન્ટ્સ!'
  },
  ml: {
    title: 'എന്റെ റിവാർഡുകൾ',
    subtitle: 'പരാതികൾ പരിഹരിച്ചതിന് ലഭിച്ച പോയിന്റുകൾ ബസ്/മെട്രോ പാസുകൾക്കായി ഉപയോഗിക്കുക.',
    balanceLabel: 'ആകെ പോയിന്റുകൾ',
    ptsLabel: 'പോയിന്റ്',
    monthLabel: 'ഈ മാസം',
    tierLabel: 'ലെവൽ',
    qrTitle: 'മെട്രോ/ബസ് ഡിജിറ്റൽ പാസ്',
    qrSubtitle: 'ഗേറ്റിൽ സ്കാൻ ചെയ്യുക',
    expiresLabel: 'കാലാവധി',
    fareTypeLabel: 'ടിക്കറ്റ് രീതി',
    reportsTitle: 'ഇടപാടുകൾ',
    viewAllBtn: 'എല്ലാം കാണുക',
    worksReportTitle: 'പരാതികൾ നൽകുക',
    worksReportDesc: 'പ്രശ്നങ്ങൾ അറിയിച്ച് കൂടുതൽ പോയിന്റുകൾ നേടുക.',
    worksTransitTitle: 'പാസുകൾ വാങ്ങുക',
    worksTransitDesc: 'പോയിന്റുകൾ ഉപയോഗിച്ച് ഡിജിറ്റൽ ടിക്കറ്റുകൾ വാങ്ങുക.',
    worksLevelTitle: 'ലെവൽ ഉയർത്തുക',
    worksLevelDesc: 'കൂടുതൽ ആനുകൂല്യങ്ങൾ നേടുക.',
    storeTitle: 'റിവാർഡ് സ്റ്റോർ',
    pass200Title: 'മെട്രോ സിംഗിൾ റൈഡ് പാസ്',
    pass200Desc: '200 പോയിന്റ് • 2 മണിക്കൂർ സമയത്തേക്ക് സാധുതയുള്ളത്.',
    pass500Title: 'ബസ് ഡേ പാസ്',
    pass500Desc: '500 പോയിന്റ് • 24 മണിക്കൂർ സമയത്തേക്ക് പരിധിയില്ലാത്ത യാത്ര.',
    redeemSuccess: 'ടിക്കറ്റ് വിജയകരമായി വാങ്ങി! വാലറ്റിൽ ലഭ്യമാണ്.',
    redeemFail: 'ആവശ്യത്തിന് പോയിന്റുകൾ ഇല്ല!'
  },
  pa: {
    title: 'ਮੇਰੇ ਇਨਾਮ',
    subtitle: 'ਆਪਣੇ ਅੰਕਾਂ ਨੂੰ ਬੱਸ/ਮੈਟਰੋ ਪਾਸ ਵਿੱਚ ਬਦਲੋ।',
    balanceLabel: 'ਕੁੱਲ ਬੈਲੰਸ',
    ptsLabel: 'ਅੰਕ',
    monthLabel: 'ਇਸ ਮਹੀਨੇ',
    tierLabel: 'ਪੱਧਰ',
    qrTitle: 'ਸਰਗਰਮ ਟ੍ਰੈਵਲ ਪਾਸ',
    qrSubtitle: 'ਐਂਟਰੀ ਲਈ ਗੇਟ ਤੇ ਸਕੈਨ ਕਰੋ',
    expiresLabel: 'ਮਿਆਦ',
    fareTypeLabel: 'ਕਿਰਾਏ ਦੀ ਕਿਸਮ',
    reportsTitle: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀਆਂ',
    viewAllBtn: 'ਸਭ ਦੇਖੋ',
    worksReportTitle: 'ਸਮੱਸਿਆਵਾਂ ਦਰਜ ਕਰੋ',
    worksReportDesc: 'ਸ਼ਿਕਾਇਤਾਂ ਦਰਜ ਕਰੋ ਅਤੇ ਅੰਕ ਹਾਸਲ ਕਰੋ।',
    worksTransitTitle: 'ਪਾਸ ਹਾਸਲ ਕਰੋ',
    worksTransitDesc: 'ਅੰਕਾਂ ਨੂੰ ਤੁਰੰਤ ਡਿਜੀਟਲ ਪਾਸ ਵਿੱਚ ਬਦਲੋ।',
    worksLevelTitle: 'ਲੈਵਲ ਅੱਪ',
    worksLevelDesc: 'ਵੱਡੇ ਇਨਾਮ ਪ੍ਰਾਪਤ ਕਰੋ।',
    storeTitle: 'ਪੁਆਇੰਟਸ ਸਟੋਰ',
    pass200Title: 'ਮੈਟਰੋ ਸਿੰਗਲ ਰਾਈਡ ਪਾਸ',
    pass200Desc: '200 ਅੰਕ • 2 ਘੰਟੇ ਲਈ ਸਾਰੇ ਰੂਟਾਂ ਤੇ ਮਾਨਤਾ।',
    pass500Title: 'ਬੱਸ ਡੇ ਪਾਸ',
    pass500Desc: '500 ਅੰਕ • 24 ਘੰਟੇ ਲਈ ਬੇਅੰਤ ਸਫ਼ਰ।',
    redeemSuccess: 'ਪਾਸ ਸਫ਼ਲਤਾਪੂਰਵਕ ਮਿਲ ਗਿਆ! ਵਾਲਿਟ ਵਿੱਚ ਚੈੱਕ ਕਰੋ।',
    redeemFail: 'ਲੋੜੀਂਦੇ ਅੰਕ ਨਹੀਂ ਹਨ!'
  },
  or: {
    title: 'ମୋର ପୁରସ୍କାର',
    subtitle: 'ଆପଣଙ୍କ ପଏଣ୍ଟକୁ ବସ୍ କିମ୍ବା ମେଟ୍ରୋ ପାସ୍‌ରେ ପରିଣତ କରନ୍ତୁ।',
    balanceLabel: 'ମୋଟ ପଏଣ୍ଟ୍',
    ptsLabel: 'ପଏଣ୍ଟ୍',
    monthLabel: 'ଏହି ମାସ',
    tierLabel: 'ସ୍ତର',
    qrTitle: 'ସକ୍ରିୟ ଯାତ୍ରା ପାସ୍',
    qrSubtitle: 'ପ୍ରବେଶ ପାଇଁ ଗେଟ୍‌ରେ ସ୍କାନ କରନ୍ତୁ',
    expiresLabel: 'ଅବଧି',
    fareTypeLabel: 'ଯାତ୍ରା ପ୍ରକାର',
    reportsTitle: 'ଇତିହାସ',
    viewAllBtn: 'ସବୁ ଦେଖନ୍ତୁ',
    worksReportTitle: 'ସମସ୍ୟା ଦାଖଲ',
    worksReportDesc: 'ସମସ୍ୟା ଦାଖଲ କରନ୍ତು ଏବଂ ପଏଣ୍ଟ୍ ପାଆନ୍ତୁ।',
    worksTransitTitle: 'ପାସ୍ କିଣନ୍ତୁ',
    worksTransitDesc: 'ପଏଣ୍ଟ୍ ବ୍ୟବହାର କରି ଯାତ୍ରା ପାସ୍ କିଣନ୍ତୁ।',
    worksLevelTitle: 'ସ୍ତର ବୃଦ୍ଧି',
    worksLevelDesc: 'ଅଧିକ ସୁବିଧା ହାସଲ କରନ୍ତୁ।',
    storeTitle: 'ପଏଣ୍ଟ୍ ଷ୍ଟୋର୍',
    pass200Title: 'ମେଟ୍ରୋ ସିଙ୍ଗଲ୍ ରାଇଡ୍ ପାସ୍',
    pass200Desc: '୨०० ପଏଣ୍ଟ୍ • ୨ ଘଣ୍ଟା ପାଇଁ ସମସ୍ତ ମାର୍ଗରେ ବୈଧ।',
    pass500Title: 'ବସ୍ ଡେ ପାସ୍',
    pass500Desc: '୫०० ପଏଣ୍ଟ୍ • ୨୪ ଘଣ୍ଟା ପାଇଁ ଅସୀମିତ ଯାତ୍ରା।',
    redeemSuccess: 'ପାସ୍ ସଫଳତାର ସହ କିଣାଗଲା! ୱାଲେଟ୍ ଦେଖନ୍ତୁ।',
    redeemFail: 'ଯଥେଷ୍ଟ ପଏଣ୍ಟ್୍ ନାହିଁ!'
  },
  as: {
    title: 'মোৰ পুৰস্কাৰসমূহ',
    subtitle: 'আপোনাৰ পইণ্টসমূহ বাছ বা মেট্ৰ’ পাছৰ বাবে ব্যৱহাৰ কৰক।',
    balanceLabel: 'মুঠ পইণ্ট',
    ptsLabel: 'পইণ্ট',
    monthLabel: 'এই মাহত',
    tierLabel: 'খাপ',
    qrTitle: 'সক্ৰিয় ভ্ৰমণ পাছ',
    qrSubtitle: 'প্ৰৱেশৰ বাবে গেটত স্কেন কৰক',
    expiresLabel: 'মেয়াদ',
    fareTypeLabel: 'ভ্ৰমণৰ ধৰণ',
    reportsTitle: 'লেনদেনসমূহ',
    viewAllBtn: 'সকলো চাওক',
    worksReportTitle: 'অভিযোগ দাখিল',
    worksReportDesc: 'সমস্যা জনাই অধিক পইণ্ট অৰ্জন কৰক।',
    worksTransitTitle: 'পাছ ক্ৰয় কৰক',
    worksTransitDesc: 'পইণ্ট ব্যৱহাৰ কৰি ডিজিটেল পাছ ক্ৰয় কৰক।',
    worksLevelTitle: 'খাপ উন্নত কৰক',
    worksLevelDesc: 'অধিক সুবিধা লাভ কৰক।',
    storeTitle: 'ৰিৱাৰ্ড ষ্ট’ৰ',
    pass200Title: 'মেট্ৰ’ চিংগল ৰাইড পাছ',
    pass200Desc: '২০০ পইণ্ট • ২ ঘণ্টাৰ বাবে সকলো পথতে প্ৰযোজ্য।',
    pass500Title: 'বাছ ডে পাছ',
    pass500Desc: '৫০০ পইণ্ট • ২৪ ঘণ্টাৰ বাবে সীমাহীন ভ্ৰমণ।',
    redeemSuccess: 'পাছ সফলতাৰে ক্ৰয় কৰা হ’ল! ৱালেটত পৰীক্ষা কৰক।',
    redeemFail: 'পৰ্যাপ্ত পইণ্ট নাই!'
  }
};
