// Static string constants for the Login feature.
// Centralises all user-visible text so they can be changed in one place.
export const LOGIN_STRINGS = {
  pageTitle:       'Sign in to Command Center',
  brandName:       'Praja Disha',
  googleBtn:       'Continue with Google',
  divider:         'or',
  radioPhone:      'Phone Number',
  radioEmail:      'Email Address',
  phonePlaceholder:'Mobile number',
  emailPlaceholder:'Email address',
  sendOtp:         'Send OTP',
  termsPrefix:     'I agree to the ',
  termsLink:       'governance protocols',
  termsSuffix:     ' and verify my identity for administrative access.',
  noAccount:       'Need an account? ',
  contactAdmin:    'Contact System Admin',
  footerCopy:      '© 2026 Praja Disha Governance Platform',
  helpCenter:      'Help Center',
  privacyPolicy:   'Privacy Policy',
  termsOfService:  'Terms of Service',
  secureEnv:       'Secure Environment',
  errorInvalidOrNotAllowed: 'Login failed. You must be an active officer assigned to an organization or department.',
  otpPageTitle:    'Verification Code',
  otpPageSubtitle: 'A 6-digit OTP has been sent to +91 9999988888.',
  otpLabel:        'One-Time Password',
  otpPlaceholder:  'Enter OTP code',
  verifyOtpBtn:    'Verify & Enter',
  defaultOtpValue: '123456',
  demoWarningTitle:'Demo Info',
  demoWarningMessage: 'jplease use only the default phone number 9999988888 to login for the demo',
  closeBtn:        'Understood',
  backBtn:         'Back to Login',
};
