const en = {
  backBtnTooltip: 'Back to Tickets',
  ticketNumberPrefix: 'Ticket #',
  resolvedStatus: 'Resolved',
  reportedStatus: 'Reported',
  assignedStatus: 'Assigned',
  inProgressStatus: 'In Progress',
  submittedStatus: 'Submitted',
  feedbackTitle: 'Share your feedback',
  feedbackPrompt: 'How would you rate the resolution of this issue?',
  feedbackCommentLabel: 'Comments (Optional)',
  feedbackCommentPlaceholder: 'Tell us about your experience...',
  submitFeedbackBtn: 'Submit Feedback',
  reopenBtn: 'Not satisfied? Reopen Ticket',
  logTitle: 'Communication Log',
  messagesCountSuffix: ' Messages',
  chatDisabledPrompt: 'Cannot send new messages on resolved tickets.',
  chatDisabledSubtext: 'Ticket is resolved. Reopen to chat...',
  noTicketFound: 'Ticket not found.',
  feedbackSubmitted: 'Thank you for your feedback!'
};

export const TICKET_DETAILS_STRINGS: Record<string, typeof en> = {
  en,
  hi: {
    backBtnTooltip: 'टिकटों पर वापस जाएं',
    ticketNumberPrefix: 'टिकट #',
    resolvedStatus: 'हल किया गया',
    reportedStatus: 'रिपोर्ट की गई',
    assignedStatus: 'सौंपा गया',
    inProgressStatus: 'प्रगति पर है',
    submittedStatus: 'जमा किया गया',
    feedbackTitle: 'अपनी प्रतिक्रिया साझा करें',
    feedbackPrompt: 'आप इस समस्या के समाधान को कैसे रेट करेंगे?',
    feedbackCommentLabel: 'टिप्पणियाँ (वैकल्पिक)',
    feedbackCommentPlaceholder: 'हमें अपने अनुभव के बारे में बताएं...',
    submitFeedbackBtn: 'प्रतिक्रिया भेजें',
    reopenBtn: 'संतुष्ट नहीं हैं? टिकट दोबारा खोलें',
    logTitle: 'संचार लॉग',
    messagesCountSuffix: ' संदेश',
    chatDisabledPrompt: 'हल किए गए टिकटों पर नए संदेश नहीं भेज सकते।',
    chatDisabledSubtext: 'टिकट हल हो गया है। चैट करने के लिए दोबारा खोलें...',
    noTicketFound: 'टिकट नहीं मिला।',
    feedbackSubmitted: 'आपकी प्रतिक्रिया के लिए धन्यवाद!'
  },
  kn: {
    backBtnTooltip: 'ಟಿಕೆಟ್‌ಗಳಿಗೆ ಮರಳಿ',
    ticketNumberPrefix: 'ಟಿಕೆಟ್ #',
    resolvedStatus: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    reportedStatus: 'ವರದಿಯಾಗಿದೆ',
    assignedStatus: 'ನಿಯೋಜಿಸಲಾಗಿದೆ',
    inProgressStatus: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    submittedStatus: 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
    feedbackTitle: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    feedbackPrompt: 'ಈ ಸಮಸ್ಯೆಯ ಪರಿಹಾರವನ್ನು ನೀವು ಹೇಗೆ ರೇಟ್ ಮಾಡುತ್ತೀರಿ?',
    feedbackCommentLabel: 'ಪ್ರತಿಕ್ರಿಯೆಗಳು (ಐಚ್ಛಿಕ)',
    feedbackCommentPlaceholder: 'ನಿಮ್ಮ ಅನುಭವದ ಬಗ್ಗೆ ನಮಗೆ ತಿಳಿಸಿ...',
    submitFeedbackBtn: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
    reopenBtn: 'ತೃಪ್ತಿಯಿಲ್ಲವೇ? ಟಿಕೆಟ್ ಮರುತೆರೆಯಿರಿ',
    logTitle: 'ಸಂವಹನ ಲಾಗ್',
    messagesCountSuffix: ' ಸಂದೇಶಗಳು',
    chatDisabledPrompt: 'ಪರಿಹರಿಸಲಾದ ಟಿಕೆಟ್‌ಗಳಲ್ಲಿ ಹೊಸ ಸಂದೇಶಗಳನ್ನು ಕಳುಹಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.',
    chatDisabledSubtext: 'ಟಿಕೆಟ್ ಪರಿಹರಿಸಲಾಗಿದೆ. ಚಾಟ್ ಮಾಡಲು ಮರುತೆರೆಯಿರಿ...',
    noTicketFound: 'ಟಿಕೆಟ್ ಕಂಡುಬಂದಿಲ್ಲ.',
    feedbackSubmitted: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!'
  },
  bn: {
    backBtnTooltip: 'টিকিটে ফিরে যান',
    ticketNumberPrefix: 'টিকিট #',
    resolvedStatus: 'মীমাংসিত',
    reportedStatus: 'রিপোর্ট করা হয়েছে',
    assignedStatus: 'বরাদ্দ করা হয়েছে',
    inProgressStatus: 'চলমান',
    submittedStatus: 'জমা দেওয়া হয়েছে',
    feedbackTitle: 'আপনার মতামত শেয়ার করুন',
    feedbackPrompt: 'এই সমস্যার সমাধানকে আপনি কীভাবে মূল্যায়ন করবেন?',
    feedbackCommentLabel: 'মন্তব্য (ঐচ্ছিক)',
    feedbackCommentPlaceholder: 'আপনার অভিজ্ঞতা সম্পর্কে বলুন...',
    submitFeedbackBtn: 'মতামত জমা দিন',
    reopenBtn: 'সন্তুষ্ট নন? টিকিট আবার খুলুন',
    logTitle: 'যোগাযোগের বিবরণ',
    messagesCountSuffix: ' বার্তা',
    chatDisabledPrompt: 'মীমাংসিত টিকিটে নতুন বার্তা পাঠানো যাবে না।',
    chatDisabledSubtext: 'টিকিট সমাধান করা হয়েছে। চ্যাট করতে আবার খুলুন...',
    noTicketFound: 'টিকিট পাওয়া যায়নি।',
    feedbackSubmitted: 'আপনার মতামতের জন্য ধন্যবাদ!'
  },
  ta: {
    backBtnTooltip: 'புகார்களுக்குத் திரும்பு',
    ticketNumberPrefix: 'புகார் #',
    resolvedStatus: 'தீர்க்கப்பட்டது',
    reportedStatus: 'புகாரளிக்கப்பட்டது',
    assignedStatus: 'ஒதுக்கப்பட்டது',
    inProgressStatus: 'செயல்பாட்டில்',
    submittedStatus: 'சமர்ப்பிக்கப்பட்டது',
    feedbackTitle: 'உங்கள் கருத்துக்களைப் பகிரவும்',
    feedbackPrompt: 'இந்த பிரச்சினையின் தீர்வை எவ்வாறு மதிப்பிடுவீர்கள்?',
    feedbackCommentLabel: 'கருத்துகள் (விருப்பத்திற்குரியது)',
    feedbackCommentPlaceholder: 'உங்கள் அனுபவத்தைப் பற்றி எங்களிடம் கூறுங்கள்...',
    submitFeedbackBtn: 'கருத்தைச் சமர்ப்பி',
    reopenBtn: 'திருப்தி இல்லையா? புகாரை மீண்டும் திறக்கவும்',
    logTitle: 'தொடர்பு பதிவு',
    messagesCountSuffix: ' செய்திகள்',
    chatDisabledPrompt: 'தீர்க்கப்பட்ட புகார்களில் புதிய செய்திகளை அனுப்ப முடியாது.',
    chatDisabledSubtext: 'புகார் தீர்க்கப்பட்டது. அரட்டையடிக்க மீண்டும் திறக்கவும்...',
    noTicketFound: 'புகார் கண்டறியப்படவில்லை.',
    feedbackSubmitted: 'உங்கள் கருத்துக்கு நன்றி!'
  },
  te: {
    backBtnTooltip: 'టిక్కెట్లకు తిరిగి వెళ్లండి',
    ticketNumberPrefix: 'టికెట్ #',
    resolvedStatus: 'పరిష్కరించబడింది',
    reportedStatus: 'నివేదించబడింది',
    assignedStatus: 'కేటాయించబడింది',
    inProgressStatus: 'పురోగతిలో ఉంది',
    submittedStatus: 'సమర్పించబడింది',
    feedbackTitle: 'మీ అభిప్రాయాన్ని పంచుకోండి',
    feedbackPrompt: 'ఈ సమస్య పరిష్కారాన్ని మీరు ఎలా రేట్ చేస్తారు?',
    feedbackCommentLabel: 'వ్యాఖ్యలు (ఐచ్ఛికం)',
    feedbackCommentPlaceholder: 'మీ అనుభవం గురించి మాకు చెప్పండి...',
    submitFeedbackBtn: 'అభిప్రాయాన్ని సమర్పించండి',
    reopenBtn: 'సంతృప్తి చెందలేదా? టికెట్ మళ్లీ తెరవండి',
    logTitle: 'కమ్యూనిเคషన్ లాగ్',
    messagesCountSuffix: ' సందేశాలు',
    chatDisabledPrompt: 'పరిష్కరించబడిన టిక్కెట్లపై కొత్త సందేశాలను పంపలేరు.',
    chatDisabledSubtext: 'టికెట్ పరిష్కరించబడింది. చాట్ చేయడానికి మళ్లీ తెరవండి...',
    noTicketFound: 'టికెట్ కనుగొనబడలేదు.',
    feedbackSubmitted: 'మీ అభిప్రాయానికి ధన్యవాదాలు!'
  },
  mr: {
    backBtnTooltip: 'तिकीटांवर परत जा',
    ticketNumberPrefix: 'तिकीट #',
    resolvedStatus: 'निराकरण झाले',
    reportedStatus: 'नोंदवलेले',
    assignedStatus: 'नियुक्त केलेले',
    inProgressStatus: 'प्रगतीपथावर',
    submittedStatus: 'सबमिट केलेले',
    feedbackTitle: 'तुमचा अभिप्राय सामायिक करा',
    feedbackPrompt: 'या समस्येच्या निराकरणाचे तुम्ही कसे मूल्यांकन कराल?',
    feedbackCommentLabel: 'टिप्पण्या (पर्यायी)',
    feedbackCommentPlaceholder: 'आम्हाला तुमच्या अनुभवाबद्दल सांगा...',
    submitFeedbackBtn: 'अभिप्राय सबमिट करा',
    reopenBtn: 'समाधानी नाही? तिकीट पुन्हा उघडा',
    logTitle: 'संवाद लॉग',
    messagesCountSuffix: ' संदेश',
    chatDisabledPrompt: 'निराकरण झालेल्या तिकिटांवर नवीन संदेश पाठवता येत नाहीत.',
    chatDisabledSubtext: 'तिकीट सोडवले गेले आहे. चॅट करण्यासाठी पुन्हा उघडा...',
    noTicketFound: 'तिकीट सापडले नाही.',
    feedbackSubmitted: 'तुमच्या अभिप्रायाबद्दल धन्यवाद!'
  },
  ur: {
    backBtnTooltip: 'ٹکٹوں پر واپس جائیں',
    ticketNumberPrefix: 'ٹکٹ #',
    resolvedStatus: 'حل شدہ',
    reportedStatus: 'رپورٹ شدہ',
    assignedStatus: 'مقرر شدہ',
    inProgressStatus: 'جاری ہے',
    submittedStatus: 'جمع شدہ',
    feedbackTitle: 'اپنی رائے شیئر کریں',
    feedbackPrompt: 'آپ اس مسئلے کے حل کو کیا ریٹنگ دیں گے؟',
    feedbackCommentLabel: 'رائے (اختیاری)',
    feedbackCommentPlaceholder: 'ہمیں اپنے تجربے کے بارے میں بتائیں...',
    submitFeedbackBtn: 'رائے جمع کروائیں',
    reopenBtn: 'مطمئن نہیں؟ ٹکٹ دوبارہ کھولیں',
    logTitle: 'گفتگو کا لاگ',
    messagesCountSuffix: ' پیغامات',
    chatDisabledPrompt: 'حل شدہ ٹکٹوں پر پیغامات نہیں بھیجے جا سکتے۔',
    chatDisabledSubtext: 'ٹکٹ حل ہو چکا ہے۔ بات چیت کے لیے دوبارہ کھولیں...',
    noTicketFound: 'ٹکٹ نہیں ملا۔',
    feedbackSubmitted: 'رائے دینے کا شکریہ!'
  },
  gu: {
    backBtnTooltip: 'ટિકિટો પર પાછા જાઓ',
    ticketNumberPrefix: 'ટિકિટ #',
    resolvedStatus: 'ઉકેલાયેલ',
    reportedStatus: 'રિપોર્ટ કરેલ',
    assignedStatus: 'સોંપાયેલ',
    inProgressStatus: 'પ્રગતિમાં',
    submittedStatus: 'સબમિટ કરેલ',
    feedbackTitle: 'તમારો પ્રતિસાદ આપો',
    feedbackPrompt: 'આ સમસ્યાના ઉકેલને તમે કેવી રીતે રેટ કરશો?',
    feedbackCommentLabel: 'ટિપ્પણીઓ (વૈકલ્પિક)',
    feedbackCommentPlaceholder: 'તમારા અનુભવ વિશે અમને જણાવો...',
    submitFeedbackBtn: 'પ્રતિસાદ સબમिट કરો',
    reopenBtn: 'સંતોષ નથી? ટિકિટ ફરીથી ખોલો',
    logTitle: 'સંચાર લોગ',
    messagesCountSuffix: ' સંદેશાઓ',
    chatDisabledPrompt: 'ઉકેલાયેલી ટિકિટો પર નવા સંદેશા મોકલી શકાતા નથી.',
    chatDisabledSubtext: 'ટિકિટ ઉકેલાઈ ગઈ છે. ચેટ કરવા માટે ફરી ખોલો...',
    noTicketFound: 'ટિકિટ મળી નથી.',
    feedbackSubmitted: 'તમારા પ્રતિસાદ બદલ આભાર!'
  },
  ml: {
    backBtnTooltip: 'ടിക്കറ്റുകളിലേക്ക് മടങ്ങുക',
    ticketNumberPrefix: 'ടിക്കറ്റ് #',
    resolvedStatus: 'പരിഹരിച്ചു',
    reportedStatus: 'റിപ്പോർട്ട് ചെയ്തു',
    assignedStatus: 'ചുമതലപ്പെടുത്തി',
    inProgressStatus: 'നടന്നുകൊണ്ടിരിക്കുന്നു',
    submittedStatus: 'സമർപ്പിച്ചു',
    feedbackTitle: 'അഭിപ്രായം പങ്കിടുക',
    feedbackPrompt: 'പ്രശ്ന പരിഹാരം എങ്ങനെ വിലയിരുത്തുന്നു?',
    feedbackCommentLabel: 'അഭിപ്രായങ്ങൾ (നിർബന്ധമില്ല)',
    feedbackCommentPlaceholder: 'അനുഭവം പങ്കുവെക്കുക...',
    submitFeedbackBtn: 'അഭിപ്രായം സമർപ്പിക്കുക',
    reopenBtn: 'തൃപ്തരല്ലേ? ടിക്കറ്റ് വീണ്ടും തുറക്കുക',
    logTitle: 'ആശയവിനിമയ ലോഗ്',
    messagesCountSuffix: ' സന്ദേശങ്ങൾ',
    chatDisabledPrompt: 'പരിഹരിച്ച ടിക്കറ്റുകളിൽ സന്ദേശം അയക്കാൻ കഴിയില്ല.',
    chatDisabledSubtext: 'ടിക്കറ്റ് പരിഹരിച്ചു. സംസാരിക്കാൻ വീണ്ടും തുറക്കുക...',
    noTicketFound: 'ടിക്കറ്റ് കണ്ടെത്തിയില്ല.',
    feedbackSubmitted: 'അഭിപ്രായം രേഖപ്പെടുത്തിയതിന് നന്ദി!'
  },
  pa: {
    backBtnTooltip: 'ਟਿਕਟਾਂ ਤੇ ਵਾਪਸ ਜਾਓ',
    ticketNumberPrefix: 'ਟਿਕਟ #',
    resolvedStatus: 'ਹੱਲ ਹੋਇਆ',
    reportedStatus: 'ਰਿਪੋਰਟ ਹੋਇਆ',
    assignedStatus: 'ਸੌਂਪਿਆ ਗਿਆ',
    inProgressStatus: 'ਜਾਰੀ ਹੈ',
    submittedStatus: 'ਜਮ੍ਹਾਂ ਹੋਇਆ',
    feedbackTitle: 'ਆਪਣੀ ਪ੍ਰਤੀਕਿਰਿਆ ਸਾਂਝੀ ਕਰੋ',
    feedbackPrompt: 'ਤੁਸੀਂ ਇਸ ਹੱਲ ਨੂੰ ਕਿਵੇਂ ਰੇਟ ਕਰੋਗੇ?',
    feedbackCommentLabel: 'ਟਿੱਪਣੀਆਂ (ਵਿਕਲਪਿਕ)',
    feedbackCommentPlaceholder: 'ਸਾਨੂੰ ਆਪਣੇ ਅਨੁਭਵ ਬਾਰੇ ਦੱਸੋ...',
    submitFeedbackBtn: 'ਫੀਡਬੈਕ ਭੇਜੋ',
    reopenBtn: 'ਸੰਤੁਸ਼ਟ ਨਹੀਂ? ਟਿਕਟ ਦੁਬਾਰਾ ਖੋਲ੍ਹੋ',
    logTitle: 'ਗੱਲਬਾਤ ਦਾ ਵੇਰਵਾ',
    messagesCountSuffix: ' ਸੁਨੇਹੇ',
    chatDisabledPrompt: 'ਹੱਲ ਹੋਈਆਂ ਟਿਕਟਾਂ ਤੇ ਸੁਨੇਹੇ ਨਹੀਂ ਭੇਜੇ ਜਾ ਸਕਦੇ।',
    chatDisabledSubtext: 'ਟਿਕਟ ਹੱਲ ਹੋ ਚੁੱਕੀ ਹੈ। ਗੱलਬਾਤ ਲਈ ਦੁਬਾਰਾ ਖੋਲ੍ਹੋ...',
    noTicketFound: 'ਟਿਕਟ ਨਹੀਂ ਮਿਲੀ।',
    feedbackSubmitted: 'ਤੁਹਾਡੇ ਫੀਡਬੈਕ ਲਈ ਧੰਨਵਾਦ!'
  },
  or: {
    backBtnTooltip: 'ଟିକେଟ୍ ପୃଷ୍ଠାକୁ ଫେରନ୍ତୁ',
    ticketNumberPrefix: 'ଟିକେଟ୍ #',
    resolvedStatus: 'ସମାଧାନ ହୋଇଛି',
    reportedStatus: 'ରିପୋର୍ଟ ହୋଇଛି',
    assignedStatus: 'ଅର୍ପଣ କରାଯାଇଛି',
    inProgressStatus: 'କାର୍ଯ୍ୟ ଚାଲିଛି',
    submittedStatus: 'ଦାଖଲ ହୋଇଛି',
    feedbackTitle: 'ଆପଣଙ୍କ ମତାମତ ଦିଅନ୍ତୁ',
    feedbackPrompt: 'ଏହି ସମାଧାନକୁ ଆପଣ କେତେ ରେଟିଂ ଦେବେ?',
    feedbackCommentLabel: 'ମତାମତ (ଇଚ୍ଛାଧୀନ)',
    feedbackCommentPlaceholder: 'ଆପଣଙ୍କ ଅନୁଭୂତି ବିଷୟରେ ଲେଖନ୍ତୁ...',
    submitFeedbackBtn: 'ମତାମત ଦାଖଲ କରନ୍ତು',
    reopenBtn: 'ସନ୍ତୁଷ୍ଟ ନାହାନ୍ତି? ଟିକେଟ୍ ପୁଣି ଖୋଲନ୍ତୁ',
    logTitle: 'ଯୋଗାଯୋଗ ବିବରଣୀ',
    messagesCountSuffix: ' ବାର୍ତ୍ତା',
    chatDisabledPrompt: 'ସମାଧାନ ହୋଇଥିବା ଟିକେଟ୍‌ରେ ବାର୍ତ୍ତା ପଠାଯାଇପାରିବ ନାହିଁ।',
    chatDisabledSubtext: 'ଟିକେଟ୍ ସମାଧାନ ହୋଇଛି। ବାର୍ତ୍ତାଳାପ ପାଇଁ ପୁଣି ଖୋଲନ୍ତୁ...',
    noTicketFound: 'ଟିକେଟ୍ ମିଳିଲା ନାହିଁ।',
    feedbackSubmitted: 'ମତାମତ ପାଇଁ ଧନ୍ୟବାଦ!'
  },
  as: {
    backBtnTooltip: 'টিকটসমূহলৈ ঘূৰি যাওক',
    ticketNumberPrefix: 'টিকট #',
    resolvedStatus: 'সমাধান হোৱা',
    reportedStatus: 'অভিযোগ হোৱা',
    assignedStatus: 'অৰ্পণ কৰা',
    inProgressStatus: 'চলতি অৱস্থা',
    submittedStatus: 'দাখিল কৰা',
    feedbackTitle: 'আপোনাৰ মতামত জনাব',
    feedbackPrompt: 'এই সমাধানটোক কেনেকৈ মূল্যায়ন কৰিব?',
    feedbackCommentLabel: 'মন্তব্য (ঐচ্ছিক)',
    feedbackCommentPlaceholder: 'আপোনাৰ অভিজ্ঞতা বৰ্ণনা কৰক...',
    submitFeedbackBtn: 'মতামত পঠিয়াওক',
    reopenBtn: 'সন্তুষ্ট নহয়? টিকট পুনৰ খোলক',
    logTitle: 'যোগাযোগৰ তথ্য',
    messagesCountSuffix: ' বাৰ্তাসমূহ',
    chatDisabledPrompt: 'সমাধান হোৱা টিকটত বাৰ্তা পঠিয়াব নোৱাৰি।',
    chatDisabledSubtext: 'টিকট সমাধান কৰা হৈছে। যোগাযোগৰ বাবে পুনৰ খোলক...',
    noTicketFound: 'টিকট বিচাৰি পোৱা নগ’ল।',
    feedbackSubmitted: 'আপোনাৰ মতামতৰ বাবে ধন্যবাদ!'
  }
};
