/** Static UI strings for the Dashboard features component. */
export const DASHBOARD_STRINGS = {
  pageTitle: 'Command Center',
  pageSubtitle: 'Real-time operational triage and AI insights.',
  actions: {
    exportReport: 'Export Report',
    newTask: 'New Task',
  },
  stats: {
    awaitingAiTitle: 'Awaiting AI Review',
    awaitingAiSubtitle: '+12% vs yesterday',
    dueTodayTitle: 'Due Today / Overdue',
    dueTodaySubtitle: 'Critical Attention Required',
    myDeptTitle: 'My Dept Assignments',
    myDeptSubtitle: 'Active workload',
  },
  triageTable: {
    title: 'Central Triage',
    searchPlaceholder: 'Search tasks, priorities, or IDs...',
    headers: {
      taskId: 'Task ID',
      titleContext: 'Title & Context',
      priority: 'Priority',
      assignment: 'Assignment',
      dueDate: 'Due Date',
      status: 'Status',
    },
    filterPlaceholders: {
      taskId: 'Filter ID',
      titleContext: 'Filter Title',
      priorityAll: 'All Priorities',
      priorityP0: 'P0',
      priorityP1: 'P1',
      priorityP2: 'P2',
      assignment: 'Filter Dept',
      assignmentSearch: 'Search departments...',
      assignmentSelected: 'selected',
      assignmentSelectAll: 'Select All',
      assignmentClearAll: 'Clear All',
      dueDate: 'Filter Date',
      statusAll: 'All Statuses',
      statusAiPending: 'Awaiting AI Review',
      statusInProgress: 'In Progress',
      statusDrafting: 'Drafting',
      statusCompleted: 'Completed',
    },
    pagination: {
      showingLabelPrefix: 'Showing',
      showingLabelMiddle: 'to',
      showingLabelOf: 'of',
      showingLabelSuffix: 'items',
    },
    emptyState: 'No matching tasks found in Central Triage.',
    duplicateTooltip: 'This ticket is grouped with other duplicate reports in the same area. Click to filter.',
    filterGroupLabel: 'Filtering by Group:',
    clearFilterLabel: 'Clear',
    unassigned: 'Unassigned',
  },
  footer: {
    brandCopy: 'Praja Disha Governance Suite © 2026',
    statusLabel: 'System Status: Operational',
    versionLabel: 'v4.2.1-stable',
  },
  futureFeaturePopup: {
    title: 'Coming Soon',
    message: 'This feature is currently scheduled for the next implementation phase. We appreciate your patience!',
    closeBtn: 'Got it',
  },
} as const;
