/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#444749",
        "on-secondary-container": "#57657b",
        "on-secondary-fixed": "#0d1c2f",
        "primary-container": "#00855d",
        "on-primary-fixed": "#002114",
        "secondary-container": "#d5e3fd",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485c",
        "surface-container": "#e5eeff",
        "secondary-fixed": "#d5e3fd",
        "tertiary": "#595c5e",
        "on-tertiary-container": "#fbfdff",
        "inverse-surface": "#213145",
        "background": "#f8f9ff",
        "on-surface-variant": "#3d4a42",
        "outline-variant": "#bccac0",
        "secondary-fixed-dim": "#b9c7e0",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#005137",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#191c1e",
        "on-error": "#ffffff",
        "primary": "#006948",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#727577",
        "secondary": "#515f74",
        "surface": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#006c4a",
        "tertiary-fixed-dim": "#c4c7c9",
        "primary-fixed-dim": "#68dba9",
        "surface-dim": "#cbdbf5",
        "error": "#ba1a1a",
        "surface-container-high": "#dce9ff",
        "inverse-primary": "#68dba9",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e0e3e5",
        "outline": "#6d7a72",
        "error-container": "#ffdad6",
        "on-primary-container": "#f5fff7",
        "on-background": "#0b1c30",
        "primary-fixed": "#85f8c4",
        "on-surface": "#0b1c30",
        "surface-container-highest": "#d3e4fe"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "lg": "40px",
        "margin-mobile": "16px",
        "max-width-content": "1140px",
        "sm": "12px",
        "base": "8px",
        "xs": "4px",
        "gutter": "20px",
        "margin-desktop": "auto",
        "md": "24px",
        "xl": "64px"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Atkinson Hyperlegible Next", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
