const en = {
  title: 'My Tickets',
  subtitle: 'Real-time updates on your community reports.',
  emptyState: 'No reports filed yet. Tap the plus button to file your first civic ticket.',
  infoCardTitle: 'Did you know?',
  infoCardDesc: 'Praja Disha uses AI to route your tickets to the right government department in under 3 seconds, speeding up response times by 40%.',
  infoCardBtn: 'Learn about AI Routing',
  lastUpdateLabel: 'Last update:',
  statusLabel: 'Status: Routing to Department',
  viewDetailsBtn: 'View Details',
  feedbackBtn: 'Feedback',
  completedLabel: 'Completed:',
  createTicketBtn: 'Report an Issue'
};

export const TRACK_STRINGS: Record<string, typeof en> = {
  en,
  hi: {
    title: 'मेरे टिकट',
    subtitle: 'आपकी सामुदायिक रिपोर्टों पर वास्तविक समय के अपडेट।',
    emptyState: 'अभी तक कोई रिपोर्ट दर्ज नहीं की गई है। अपना पहला नागरिक टिकट दर्ज करने के लिए प्लस बटन दबाएं।',
    infoCardTitle: 'क्या आप जानते हैं?',
    infoCardDesc: 'प्रजा दिशा आपकी शिकायतों को 3 सेकंड से भी कम समय में सही नगरपालिका विभाग में भेजने के लिए एआई का उपयोग करता है, जिससे प्रतिक्रिया समय 40% बढ़ जाता है।',
    infoCardBtn: 'एआई रूटिंग के बारे में जानें',
    lastUpdateLabel: 'अंतिम अपडेट:',
    statusLabel: 'स्थिति: विभाग को रूट किया जा रहा है',
    viewDetailsBtn: 'विवरण देखें',
    feedbackBtn: 'प्रतिक्रिया',
    completedLabel: 'पूरा किया गया:',
    createTicketBtn: 'समस्या की रिपोर्ट करें'
  },
  kn: {
    title: 'ನನ್ನ ಟಿಕೆಟ್‌ಗಳು',
    subtitle: 'ನಿಮ್ಮ ಸಮುದಾಯದ ವರದಿಗಳ ನೈಜ-ಸಮಯದ ನವೀಕರಣಗಳು.',
    emptyState: 'ಇನ್ನೂ ಯಾವುದೇ ವರದಿಗಳು ಸಲ್ಲಿಕೆಯಾಗಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ಟಿಕೆಟ್ ಸಲ್ಲಿಸಲು ಪ್ಲಸ್ ಬಟನ್ ಟ್ಯಾಪ್ ಮಾಡಿ.',
    infoCardTitle: 'ನಿಮಗೆ ತಿಳಿದಿದೆಯೇ?',
    infoCardDesc: 'ಪ್ರಜಾ ದಿಶಾ ನಿಮ್ಮ ಟಿಕೆಟ್‌ಗಳನ್ನು 3 സെക്കന്‍ಡ್‌ಗಿಂತ ಕಡಿಮೆ ಅವಧಿಯಲ್ಲಿ ಸರಿಯಾದ ಪುರಸಭೆ ಇಲಾಖೆಗೆ ವರ್ಗಾಯಿಸಲು AI ಅನ್ನು ಬಳಸುತ್ತದೆ, ಇದು ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯವನ್ನು 40% ರಷ್ಟು ವೇಗಗೊಳಿಸುತ್ತದೆ.',
    infoCardBtn: 'AI ವರ್ಗಾವಣೆ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ',
    lastUpdateLabel: 'ಕೊನೆಯ ಅಪ್ಡೇಟ್:',
    statusLabel: 'ಸ್ಥಿತಿ: ಇಲಾಖೆಗೆ ವರ್ಗಾಯಿಸಲಾಗುತ್ತಿದೆ',
    viewDetailsBtn: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    feedbackBtn: 'ಪ್ರತಿಕ್ರಿಯೆ',
    completedLabel: 'ਪੂਰਣಗೊಂಡಿದೆ:',
    createTicketBtn: 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ'
  },
  bn: {
    title: 'আমার টিকিট',
    subtitle: 'আপনার সম্প্রদায়ের রিপোর্টের রিয়েল-টাইম আপডেট।',
    emptyState: 'এখনও কোনো রিপোর্ট দাখিল করা হয়নি। আপনার প্রথম টিকিট জমা দিতে প্লাস বোতামে চাপ দিন।',
    infoCardTitle: 'আপনি কি জানেন?',
    infoCardDesc: 'প্রজা দিশা ৩ সেকেন্ডের কম সময়ে সঠিক পৌর বিভাগে আপনার টিকিট পাঠাতে এআই ব্যবহার করে, যা প্রতিক্রিয়ার গতি ৪০% বাড়িয়ে দেয়।',
    infoCardBtn: 'এআই রাউটিং সম্পর্কে জানুন',
    lastUpdateLabel: 'শেষ আপডেট:',
    statusLabel: 'অবস্থা: বিভাগে পাঠানো হচ্ছে',
    viewDetailsBtn: 'বিস্তারিত দেখুন',
    feedbackBtn: 'মতামত',
    completedLabel: 'সম্পন্ন হয়েছে:',
    createTicketBtn: 'সমস্যা রিপোর্ট করুন'
  },
  ta: {
    title: 'எனது புகார்கள்',
    subtitle: 'உங்கள் சமூகப் புகார்கள் குறித்த நிகழ்நேரப் புதுப்பிப்புகள்.',
    emptyState: 'இன்னும் புகார்கள் எதுவும் தாக்கல் செய்யப்படவில்லை. உங்களின் முதல் புகாரைத் தாக்கல் செய்ய பிளஸ் பொத்தானைத் தட்டவும்.',
    infoCardTitle: 'உங்களுக்குத் தெரியுமா?',
    infoCardDesc: 'பிரஜா திஷா AI-ஐப் பயன்படுத்தி 3 வினாடிகளுக்குள் உங்கள் புகாரை சரியான நகராட்சித் துறைக்கு அனுப்புகிறது, இது பதிலளிக்கும் நேரத்தை 40% வேகமாகாக்குகிறது.',
    infoCardBtn: 'AI ரூட்டிங் பற்றி அறியவும்',
    lastUpdateLabel: 'கடைசி புதுப்பிப்பு:',
    statusLabel: 'நிலை: துறைக்கு அனுப்பப்படுகிறது',
    viewDetailsBtn: 'விவரங்களைக் காண்க',
    feedbackBtn: 'கருத்து',
    completedLabel: 'முடிந்தது:',
    createTicketBtn: 'பிரச்சினையைப் புகாரளி'
  },
  te: {
    title: 'నా టిక్కెట్లు',
    subtitle: 'మీ కమ్యూనిటీ నివేదికలపై నిజ-సమయ నవీకరణలు.',
    emptyState: 'ఇంకా ఎలాంటి నివేదికలు దాఖలు చేయలేదు. మొదటి టికెట్ దాఖలు చేయడానికి ప్లస్ బటన్‌ను నొక్కండి.',
    infoCardTitle: 'మీకు తెలుసా?',
    infoCardDesc: 'ప్రజా దిశ మీ టిక్కెట్‌లను 3 సెకన్లలోపు సరైన మున్సిపల్ విభాగానికి చేర్చడానికి AIని ఉపయోగిస్తుంది, ఇది ప్రతిస్పందన సమయాన్ని 40% వేగవంతం చేస్తుంది.',
    infoCardBtn: 'AI రూటింగ్ గురించి తెలుసుకోండి',
    lastUpdateLabel: 'చివరి నవీకరణ:',
    statusLabel: 'స్థితి: విభాగానికి మళ్లింపు',
    viewDetailsBtn: 'వివరాలను వీక్షించండి',
    feedbackBtn: 'అభిప్రాయం',
    completedLabel: 'పూర్తయింది:',
    createTicketBtn: 'సమస్యను నివేదించండి'
  },
  mr: {
    title: 'माझी तिकिटे',
    subtitle: 'तुमच्या नागरी तक्रारींवर रिअल-टाइम अपडेट्स.',
    emptyState: 'अद्याप एकही तक्रार नोंदवलेली नाही. तुमचे पहिले तिकीट दाखल करण्यासाठी प्लस बटणावर टॅप करा.',
    infoCardTitle: 'तुम्हाला माहीत आहे का?',
    infoCardDesc: 'प्रजा दिशा तुमची तिकिटे ३ सेकंदांपेक्षा कमी वेळात योग्य महापालिका विभागाकडे वर्ग करण्यासाठी एआय वापरते, ज्यामुळे वेळेची ४०% बचत होते.',
    infoCardBtn: 'एआय राउटिंगबद्दल जाणून घ्या',
    lastUpdateLabel: 'शेवटचे अपडेट:',
    statusLabel: 'स्थिती: विभागाकडे वर्ग करत आहे',
    viewDetailsBtn: 'तपशील पहा',
    feedbackBtn: 'अभिप्राय',
    completedLabel: 'पूर्ण झाले:',
    createTicketBtn: 'समस्येची तक्रार करा'
  },
  ur: {
    title: 'میرے ٹکٹ',
    subtitle: 'آپ کے مسائل کی رپورٹس پر تازہ ترین معلومات۔',
    emptyState: 'ابھی تک کوئی رپورٹ درج نہیں کی گئی۔ اپنی پہلی رپورٹ درج کرنے کے لیے جمع کا بٹن دبائیں۔',
    infoCardTitle: 'کیا آپ جانتے ہیں؟',
    infoCardDesc: 'شہری نظام کو بہتر بنانے کے لیے آرٹیفیشل انٹیلیجنس کا استعمال کیا جاتا ہے، جس سے کام 40 فیصد تیزی سے ہوتا ہے۔',
    infoCardBtn: 'اے آئی نظام کے بارے میں جانیں',
    lastUpdateLabel: 'آخری اپ ڈیٹ:',
    statusLabel: 'حیثیت: متعلقہ شعبہ کو منتقلی',
    viewDetailsBtn: 'تفصیلات دیکھیں',
    feedbackBtn: 'رائے',
    completedLabel: 'مکمل شدہ:',
    createTicketBtn: 'مسئلہ رپورٹ کریں'
  },
  gu: {
    title: 'મારી ટિકિટો',
    subtitle: 'તમારા સામુદાયિક રિપોર્ટ પર રીઅલ-ટાઇમ અપડેટ્સ.',
    emptyState: 'હજી સુધી કોઈ ફરિયાદ નોંધાઈ નથી. તમારી પ્રથમ ટિકિટ ફાઇલ કરવા માટે પ્લસ બટન દબાવો.',
    infoCardTitle: 'શું તમે જાણો છો?',
    infoCardDesc: 'પ્રજા દિશા એઆઈ દ્વારા ૩ સેકન્ડથી ઓછા સમયમાં યોગ્ય વિભાગને ટિકિટ મોકલે છે, જેનાથી પ્રતિસાદ સમય ૪૦% સુધરે છે.',
    infoCardBtn: 'એઆઈ રાઉટિંગ વિશે જાણો',
    lastUpdateLabel: 'છેલ્લું અપડેટ:',
    statusLabel: 'સ્થિતિ: વિભાગને મોકલાઈ રહી છે',
    viewDetailsBtn: 'વિગતો જુઓ',
    feedbackBtn: 'પ્રતિસાદ',
    completedLabel: 'પૂર્ણ થયેલ:',
    createTicketBtn: 'સમસ્યા રિપોર્ટ કરો'
  },
  ml: {
    title: 'എന്റെ ടിക്കറ്റുകൾ',
    subtitle: 'പരാതികളുടെ തത്സമയ വിവരങ്ങൾ.',
    emptyState: 'പരാതികളൊന്നും ഇതുവരെ നൽകിയിട്ടില്ല. ആദ്യ പരാതി നൽകാൻ പ്ലസ് ചിഹ്നം അമർത്തുക.',
    infoCardTitle: 'നിങ്ങൾക്കറിയാമോ?',
    infoCardDesc: 'പ്രജാ ദിശ AI ഉപയോഗിച്ച് 3 സെക്കൻഡിനുള്ളിൽ ശരിയായ വകുപ്പിലേക്ക് പരാതികൾ കൈമാറുന്നു.',
    infoCardBtn: 'AI റൂട്ടിംഗിനെക്കുറിച്ച് അറിയുക',
    lastUpdateLabel: 'അവസാന മാറ്റം:',
    statusLabel: 'നില: വകുപ്പിലേക്ക് മാറ്റുന്നു',
    viewDetailsBtn: 'വിശദാംശങ്ങൾ കാണുക',
    feedbackBtn: 'അഭിപ്രായം',
    completedLabel: 'പൂർത്തിയായി:',
    createTicketBtn: 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക'
  },
  pa: {
    title: 'ਮੇਰੀਆਂ ਟਿਕਟਾਂ',
    subtitle: 'ਤੁਹਾਡੀਆਂ ਸਮੱਸਿਆਵਾਂ ਦੀ ਰਿਪੋਰਟ ਤੇ ਰੀਅਲ-ਟਾਈਮ ਅਪਡੇਟ।',
    emptyState: 'ਅਜੇ ਤੱਕ ਕੋਈ ਰਿਪੋਰਟ ਦਰਜ ਨਹੀਂ ਹੋਈ। ਪਹਿਲੀ ਟਿਕਟ ਦਰਜ ਕਰਨ ਲਈ ਪਲੱਸ ਬਟਨ ਦਬਾਓ।',
    infoCardTitle: 'ਕੀ ਤੁਸੀਂ ਜਾਣਦੇ ਹੋ?',
    infoCardDesc: 'ਪ੍ਰਜਾ ਦਿਸ਼ਾ ਤੁਹਾਡੀ ਸ਼ਿਕਾਇਤ ਨੂੰ 3 ਸੈਕਿੰਡ ਤੋਂ ਘੱਟ ਸਮੇਂ ਵਿੱਚ ਸਹੀ ਵਿਭਾਗ ਤੱਕ ਪਹੁੰਚਾਉਣ ਲਈ ਏਆਈ ਦੀ ਵਰਤੋਂ ਕਰਦਾ ਹੈ।',
    infoCardBtn: 'ਏਆਈ ਰੂਟਿੰਗ ਬਾਰੇ ਜਾਣੋ',
    lastUpdateLabel: 'ਆਖਰੀ ਅਪਡੇਟ:',
    statusLabel: 'ਸਥਿਤੀ: ਵਿਭਾਗ ਨੂੰ ਭੇਜੀ ਜਾ ਰਹੀ ਹੈ',
    viewDetailsBtn: 'ਵੇਰਵੇ ਦੇਖੋ',
    feedbackBtn: 'ਫੀਡਬੈਕ',
    completedLabel: 'ਪੂਰਾ ਹੋਇਆ:',
    createTicketBtn: 'ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ'
  },
  or: {
    title: 'ମୋର ଟିକେଟ୍',
    subtitle: 'ଆପଣଙ୍କ ସମସ୍ୟାର ସଦ୍ୟତମ ସୂଚନା।',
    emptyState: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଅଭିଯୋଗ ଦାଖଲ ହୋଇନାହିଁ। ପ୍ରଥମ ଟିକେଟ୍ ଦାଖଲ ପାଇଁ ପ୍ଲସ୍ ବଟନ୍ ଦବାନ୍ତୁ।',
    infoCardTitle: 'ଆପଣ ଜାଣନ୍ତି କି?',
    infoCardDesc: 'ପ୍ରଜା ଦିଶା AI ବ୍ୟବହାର କରି ଅଭିଯୋଗକୁ ୩ ସେକେଣ୍ଡ ମଧ୍ୟରେ ସଠିକ୍ ବିଭାଗକୁ ପଠାଇଥାଏ।',
    infoCardBtn: 'AI ସଞ୍ଚାଳନ ବିଷୟରେ ଜାଣନ୍ତୁ',
    lastUpdateLabel: 'ଶେଷ ସୂଚନା:',
    statusLabel: 'ଅବସ୍ଥା: ସମ୍ବନ୍ଧିତ ବିଭାଗକୁ ପ୍ରେରଣ',
    viewDetailsBtn: 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    feedbackBtn: 'ମତାମତ',
    completedLabel: 'ସମ୍ପନ୍ନ:',
    createTicketBtn: 'ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ'
  },
  as: {
    title: 'মোৰ টিকটসমূহ',
    subtitle: 'আপোনাৰ অভিযোগসমূহৰ সঠিক সময়ৰ তথ্য।',
    emptyState: 'এতিয়ালৈকে কোনো অভিযোগ দাখিল হোৱা নাই। প্ৰথম টিকট দাখিল কৰিবলৈ প্লাচ বুটাম টিপক।',
    infoCardTitle: 'আপুনি জানেনে?',
    infoCardDesc: 'প্ৰজা দিশাই এআই ব্যৱহাৰ কৰি ৩ চেকেণ্ডৰ ভিতৰত অভিযোগ সঠিক বিভাগলৈ প্ৰেৰণ কৰে।',
    infoCardBtn: 'এআই ৰুটিং সম্পর্কে জানক',
    lastUpdateLabel: 'শেহতীয়া আপডেট:',
    statusLabel: 'স্থিতি: বিভাগলৈ প্ৰেৰণ কৰা হৈছে',
    viewDetailsBtn: 'বিশদ তথ্য চাওক',
    feedbackBtn: 'মতামত',
    completedLabel: 'সম্পূৰ্ণ হ’ল:',
    createTicketBtn: 'অভিযোগ দাখিল কৰক'
  }
};
