const en = {
  brandName: 'Praja Disha',
  welcomeTitle: 'Welcome back',
  welcomeSubtitle: 'Sign in to access your local civic dashboard.',
  inputLabel: 'Phone Number',
  inputPlaceholder: 'Enter phone number',
  otpLabel: 'OTP Code',
  otpPlaceholder: 'Enter 6-digit OTP',
  buttonLabel: 'Login',
  sendingLabel: 'Logging in...',
  otpSentLabel: 'Success',
  termsAgreement: 'By continuing, you agree to our ',
  termsLink: 'Terms of Service',
  privacyLink: 'Privacy Policy',
  languageLabel: 'Select Language',
  helpLink: 'Need help accessing your account?',
  realAppNotification: 'In a real app, you would now see the OTP entry field.',
  dummyPhone: '9876543210',
  dummyOtp: '123456'
};

export const LOGIN_STRINGS: Record<string, typeof en> = {
  en,
  hi: {
    brandName: 'प्रजा दिशा',
    welcomeTitle: 'वापसी पर स्वागत है',
    welcomeSubtitle: 'अपने स्थानीय नागरिक डैशबोर्ड तक पहुँचने के लिए साइन इन करें।',
    inputLabel: 'फ़ोन नंबर',
    inputPlaceholder: 'फ़ोन नंबर दर्ज करें',
    otpLabel: 'ओटीपी कोड',
    otpPlaceholder: '6-अंकीय ओटीपी दर्ज करें',
    buttonLabel: 'लॉगिन',
    sendingLabel: 'लॉगिन हो रहा है...',
    otpSentLabel: 'सफलता',
    termsAgreement: 'आगे बढ़कर, आप हमारी इन शर्तों से सहमत होते हैं ',
    termsLink: 'सेवा की शर्तें',
    privacyLink: 'गोपनीयता नीति',
    languageLabel: 'भाषा चुनें',
    helpLink: 'अपने खाते तक पहुँचने में सहायता चाहिए?',
    realAppNotification: 'वास्तविक ऐप में, अब आप ओटीपी प्रविष्टि फ़ील्ड देखेंगे।',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  kn: {
    brandName: 'ಪ್ರಜಾ ದಿಶಾ',
    welcomeTitle: 'ಮರಳಿ ಸ್ವಾಗತ',
    welcomeSubtitle: 'ನಿಮ್ಮ ಸ್ಥಳೀಯ ನಾಗರಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    inputLabel: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
    inputPlaceholder: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    otpLabel: 'ಒಟಿಪಿ ಕೋಡ್',
    otpPlaceholder: '6-ಅಂಕಿಯ ಒಟಿಪಿ ನಮೂದಿಸಿ',
    buttonLabel: 'ಲಾಗಿನ್',
    sendingLabel: 'ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...',
    otpSentLabel: 'ಯಶಸ್ಸು',
    termsAgreement: 'ಮುಂದುವರಿಯುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ ನಿಯಮಗಳಿಗೆ ಒಪ್ಪುತ್ತೀರಿ ',
    termsLink: 'ಸೇವಾ ನಿಯಮಗಳು',
    privacyLink: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    languageLabel: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    helpLink: 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ಸಹಾಯ ಬೇಕೇ?',
    realAppNotification: 'ನೈಜ ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ, ನೀವು ಈಗ ಒಟಿಪಿ ನಮೂದು ಕ್ಷೇತ್ರವನ್ನು ನೋಡುತ್ತೀರಿ.',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  bn: {
    brandName: 'প্রজা দিশা',
    welcomeTitle: 'স্বাগত',
    welcomeSubtitle: 'আপনার স্থানীয় নাগরিক ড্যাশবোর্ড অ্যাক্সেস করতে সাইন ইন করুন।',
    inputLabel: 'ফোন নম্বর',
    inputPlaceholder: 'ফোন নম্বর লিখুন',
    otpLabel: 'ওটিপি কোড',
    otpPlaceholder: '৬-সংখ্যার ওটিপি লিখুন',
    buttonLabel: 'লগইন',
    sendingLabel: 'লগইন হচ্ছে...',
    otpSentLabel: 'সফলতা',
    termsAgreement: 'এগিয়ে যাওয়ার মাধ্যমে, আপনি আমাদের শর্তাবলীতে সম্মত হন ',
    termsLink: 'পরিষেবার শর্তাবলী',
    privacyLink: 'গোপনীয়তা নীতি',
    languageLabel: 'ভাষা নির্বাচন করুন',
    helpLink: 'অ্যাক্সেস করতে সাহায্য প্রয়োজন?',
    realAppNotification: 'একটি বাস্তব অ্যাপে, আপনি এখন ওটিপি এন্ট্রি ক্ষেত্রটি দেখতে পাবেন।',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  ta: {
    brandName: 'பிரஜா திஷா',
    welcomeTitle: 'நல்வரவு',
    welcomeSubtitle: 'உங்கள் உள்ளூர் குடிமை டாஷ்போர்டை அணுக உள்நுழைக.',
    inputLabel: 'தொலைபேசி எண்',
    inputPlaceholder: 'தொலைபேசி எண்ணை உள்ளிடவும்',
    otpLabel: 'OTP குறியீடு',
    otpPlaceholder: '6-இலக்க OTP ஐ உள்ளிடவும்',
    buttonLabel: 'உள்நுழை',
    sendingLabel: 'உள்நுழைகிறது...',
    otpSentLabel: 'வெற்றி',
    termsAgreement: 'தொடர்வதன் மூலம், எங்கள் விதிமுறைகளை ஏற்கிறீர்கள் ',
    termsLink: 'சேவை விதிமுறைகள்',
    privacyLink: 'தனியுரிமைக் கொள்கை',
    languageLabel: 'மொழியைத் தேர்ந்தெடு',
    helpLink: 'கணக்கை அணுக உதவி தேவையா?',
    realAppNotification: 'உண்மையான பயன்பாட்டில், நீங்கள் இப்போது OTP உள்ளீட்டு புலத்தைக் காண்பீர்கள்।',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  te: {
    brandName: 'ప్రజా దిశ',
    welcomeTitle: 'స్వాగతం',
    welcomeSubtitle: 'మీ స్థానిక పౌర డాష్‌బోర్డ్ యాక్సెస్ చేయడానికి లాగిన్ అవ్వండి.',
    inputLabel: 'ఫోన్ నంబర్',
    inputPlaceholder: 'ఫోన్ నంబర్ నమోదు చేయండి',
    otpLabel: 'OTP కోڈ',
    otpPlaceholder: '6-అంకెల OTPని నమోదు చేయండి',
    buttonLabel: 'లాగిన్',
    sendingLabel: 'లాగిన్ అవుతోంది...',
    otpSentLabel: 'విజయం',
    termsAgreement: 'కొనసాగడం ద్వారా, మీరు మా సేవా నిబంధనలను అంగీకరిస్తున్నారు ',
    termsLink: 'సేవా నిబంధనలు',
    privacyLink: 'గోప్యతా విధానం',
    languageLabel: 'భాషను ఎంచుకోండి',
    helpLink: 'ఖాతాను యాక్సెస్ చేయడానికి సహాయం కావాలా?',
    realAppNotification: 'నిజమైన యాప్‌లో, మీరు ఇప్పుడు OTP నమోదు ఫీల్డ్‌ను చూస్తారు.',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  mr: {
    brandName: 'प्रजा दिशा',
    welcomeTitle: 'पुन्हा स्वागत आहे',
    welcomeSubtitle: 'आपल्या स्थानिक नागरी डॅशबोर्डमध्ये प्रवेश करण्यासाठी साइन इन करा.',
    inputLabel: 'फोन नंबर',
    inputPlaceholder: 'फोन नंबर प्रविष्ट करा',
    otpLabel: 'ओटीपी कोड',
    otpPlaceholder: '६-अंकी ओटीपी प्रविष्ट करा',
    buttonLabel: 'लॉगिन',
    sendingLabel: 'लॉगिन होत आहे...',
    otpSentLabel: 'यशस्वी',
    termsAgreement: 'आगे चालू ठेवून, आपण आमच्या अटींशी सहमत आहात ',
    termsLink: 'सेवा अटी',
    privacyLink: 'गोपनीयता धोरण',
    languageLabel: 'भाषा निवडा',
    helpLink: 'खात्यात प्रवेश करण्यास मदत हवी आहे का?',
    realAppNotification: 'वास्तविक ॲपमध्ये, आपण आता ओटीपी प्रविष्टी फील्ड पाहाल.',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  ur: {
    brandName: 'प्रजा दिशा',
    welcomeTitle: 'خوش آمدید',
    welcomeSubtitle: 'اپنے مقامی شہری ڈیش بورڈ तक رسائی کے لیے سائن ان کریں۔',
    inputLabel: 'فون نمبر',
    inputPlaceholder: 'فون نمبر درج کریں',
    otpLabel: 'او ٹی پی کوڈ',
    otpPlaceholder: '6 ہندسوں کا او ٹی پی درج کریں',
    buttonLabel: 'لاگ ان',
    sendingLabel: 'لاگ ان ہو رہا ہے...',
    otpSentLabel: 'کامیابی',
    termsAgreement: 'جاری رکھ کر، آپ ہماری شرائط سے اتفاق کرتے ہیں ',
    termsLink: 'سروس کی شرائط',
    privacyLink: 'رازداری کی پالیسی',
    languageLabel: 'زبان منتخب کریں',
    helpLink: 'اپنے اکاؤنٹ تک رسائی میں مدد چاہیے؟',
    realAppNotification: 'اصلی ایپ میں، اب آپ کو او ٹی پی انٹری فیلڈ نظر آئے گی۔',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  gu: {
    brandName: 'પ્રજા દિશા',
    welcomeTitle: 'સ્વાગત છે',
    welcomeSubtitle: 'તમારા સ્થાનિક નાગરિક ડેશબોર્ડને ઍક્સેસ કરવા માટે સાઇન ઇન કરો.',
    inputLabel: 'ફોન નંબર',
    inputPlaceholder: 'ફોન નંબર દાખલ કરો',
    otpLabel: 'ઓટીપી કોડ',
    otpPlaceholder: '6-અંકનો ઓટીપી દાખલ કરો',
    buttonLabel: 'લોગિન',
    sendingLabel: 'લોગિન થઈ રહ્યું છે...',
    otpSentLabel: 'સફળતા',
    termsAgreement: 'આગળ વધીને, તમે અમારી શરતોથી સંમત થાઓ છો ',
    termsLink: 'સેવાની શરતો',
    privacyLink: 'ગોપનીયતા નીતિ',
    languageLabel: 'ભાષા પસંદ કરો',
    helpLink: 'ખાતામાં પ્રવેશ માટે મદદ જોઈએ છે?',
    realAppNotification: 'વાસ્તવિક એપમાં, તમે હવે ઓટીપી ફીલ્ડ જોશે.',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  ml: {
    brandName: 'പ്രജാ ദിശ',
    welcomeTitle: 'സ്വാഗതം',
    welcomeSubtitle: 'നിങ്ങളുടെ പ്രാദേശിക സിവിക് ഡാഷ്‌ബോർഡ് ആക്‌സസ് ചെയ്യാൻ സൈൻ ഇൻ ചെയ്യുക.',
    inputLabel: 'ഫോൺ നമ്പർ',
    inputPlaceholder: 'ഫോൺ നമ്പർ നൽകുക',
    otpLabel: 'ഒടിപി കോഡ്',
    otpPlaceholder: '6 അക്ക ഒടിപി നൽകുക',
    buttonLabel: 'ലോഗിൻ',
    sendingLabel: 'ലോഗിൻ ചെയ്യുന്നു...',
    otpSentLabel: 'വിജയം',
    termsAgreement: 'തുടരുന്നതിലൂടെ, നിങ്ങൾ ഞങ്ങളുടെ വ്യവസ്ഥകൾ അംഗീകരിക്കുന്നു ',
    termsLink: 'സേവന വ്യവസ്ഥകൾ',
    privacyLink: 'സ്വകാര്യതാ നയം',
    languageLabel: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    helpLink: 'അക്കൗണ്ട് ആക്സസ് ചെയ്യാൻ സഹായം വേണോ?',
    realAppNotification: 'ഒരു യഥാർത്ഥ ആപ്പിൽ, നിങ്ങൾ ഇപ്പോൾ ഒടിപി ഫീൽഡ് കാണും.',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  pa: {
    brandName: 'ਪ੍ਰਜਾ ਦਿਸ਼ਾ',
    welcomeTitle: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    welcomeSubtitle: 'ਆਪਣੇ ਸਥਾਨਕ ਨਾਗਰਿਕ ਡੈਸ਼ਬੋਰਡ ਤੱਕ ਪਹੁੰਚਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।',
    inputLabel: 'ਫ਼ੋਨ ਨੰਬਰ',
    inputPlaceholder: 'ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    otpLabel: 'ਓਟੀਪੀ ਕੋਡ',
    otpPlaceholder: '6-ਅੰਕਾਂ ਦਾ ਓਟੀਪੀ ਦਰਜ ਕਰੋ',
    buttonLabel: 'ਲੌਗਇਨ',
    sendingLabel: 'ਲੌਗਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
    otpSentLabel: 'ਸਫ਼ਲਤਾ',
    termsAgreement: 'ਜਾਰੀ ਰੱਖ ਕੇ, ਤੁਸੀਂ ਸਾਡੀਆਂ ਸ਼ਰਤਾਂ ਨਾਲ ਸਹਿਮਤ ਹੁੰਦੇ ਹੋ ',
    termsLink: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    privacyLink: 'ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ',
    languageLabel: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    helpLink: 'ਖਾਤੇ ਤੱਕ ਪਹੁੰਚਣ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    realAppNotification: 'ਅਸਲ ਐਪ ਵਿੱਚ, ਤੁਸੀਂ ਹੁਣ ਓਟੀਪੀ ਫੀਲਡ ਦੇਖੋਗੇ।',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  or: {
    brandName: 'ପ୍ରଜା ଦିଶା',
    welcomeTitle: 'ସ୍ୱାଗତ',
    welcomeSubtitle: 'ଆପଣଙ୍କର ସ୍ଥାନୀୟ ନାଗରିକ ଡ୍ୟାସବୋର୍ଡ ପ୍ରବେଶ କରିବାକୁ ସାଇନ ଇନ କରନ୍ତୁ।',
    inputLabel: 'ଫୋନ ନମ୍ବର',
    inputPlaceholder: 'ଫୋନ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ',
    otpLabel: 'ଓଟିପି କୋଡ୍',
    otpPlaceholder: '୬-ଅଙ୍କ ବିଶିଷ୍ଟ ଓଟିପି ପ୍ରବେଶ କରନ୍ତୁ',
    buttonLabel: 'ଲଗଇନ',
    sendingLabel: 'ଲଗଇନ ହେଉଛି...',
    otpSentLabel: 'ସଫଳତା',
    termsAgreement: 'ଆଗକୁ ବଢିବା ଦ୍ୱାରା, ଆପଣ ଆମର ସର୍ତ୍ତାବଳୀରେ ସହମତ ହୁଅନ୍ତି ',
    termsLink: 'ସେବା ସର୍ତ୍ତାବଳୀ',
    privacyLink: 'ଗୋପନୀୟତା ନୀତି',
    languageLabel: 'ଭାଷା ଚୟନ କରନ୍ତୁ',
    helpLink: 'ଖାତା ପ୍ରବେଶ କରିବାରେ ସାହାଯ୍ୟ ଦରକାର କି?',
    realAppNotification: 'ପ୍ରକୃତ ଆପ୍‌ରେ, ଆପଣ ବର୍ତ୍ତମାନ ଓଟିପି ଦେଖିବେ।',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  },
  as: {
    brandName: 'প্ৰজা দিশা',
    welcomeTitle: 'স্বাগতম',
    welcomeSubtitle: 'আপোনাৰ স্থানীয় নাগৰিক ডেক্সব’ৰ্ডত প্ৰৱেশ কৰিবলৈ ছাইন ইন কৰক।',
    inputLabel: 'ফোন নম্বৰ',
    inputPlaceholder: 'ফোন নম্বৰ লিখক',
    otpLabel: 'অ’টিপি ক’ড',
    otpPlaceholder: '৬-অংকৰ অ’টিപി লিখক',
    buttonLabel: 'লগইন',
    sendingLabel: 'লগইন হৈ আছে...',
    otpSentLabel: 'সফলতা',
    termsAgreement: 'আগবাঢ়ি যোৱাৰ জৰিয়তে, আপুনি আমাৰ চৰ্তাৱলীত সন্মতি জনাইছে ',
    termsLink: 'সেৱাৰ চৰ্তাৱলী',
    privacyLink: 'গোপনীয়তা নীতি',
    languageLabel: 'ভাষা বাছনি কৰক',
    helpLink: 'একাউণ্টত প্ৰৱেশ কৰিবলৈ সহায় লাগে নেকি?',
    realAppNotification: 'প্ৰকৃত অ্যাপত, আপুনি এতিয়া অ’টিপি লিখা স্থান দেখিব।',
    dummyPhone: '9876543210',
    dummyOtp: '123456'
  }
};
