const en = {
  brandName: 'Praja Disha',
  leftTitle: 'Civic power in your hands.',
  leftDesc: 'Join thousands of citizens actively shaping their community. Report issues, track resolutions, and participate in local governance with complete transparency.',
  rightTitle: 'Create Account',
  rightSubtitle: 'Register to access institutional civic services.',
  nameLabel: 'Full Name',
  namePlaceholder: 'e.g. Jane Doe',
  contactLabel: 'Verified Contact',
  verifiedBadge: 'Verified',
  termsAgreement: 'I agree to the ',
  termsLink: 'Terms of Service',
  privacyLink: 'Privacy Policy',
  submitButton: 'Create Account',
  signInLabel: 'Already have an account? ',
  signInLink: 'Sign In'
};

export const REGISTER_STRINGS: Record<string, typeof en> = {
  en,
  hi: {
    brandName: 'प्रजा दिशा',
    leftTitle: 'नागरिक शक्ति आपके हाथों में।',
    leftDesc: 'अपने समुदाय को सक्रिय रूप से आकार देने वाले हजारों नागरिकों में शामिल हों। पूर्ण पारदर्शिता के साथ मुद्दों की रिपोर्ट करें, समाधानों को ट्रैक करें और स्थानीय शासन में भाग लें।',
    rightTitle: 'खाता बनाएं',
    rightSubtitle: 'संस्थागत नागरिक सेवाओं तक पहुँचने के लिए पंजीकरण करें।',
    nameLabel: 'पूरा नाम',
    namePlaceholder: 'जैसे- राहुल कुमार',
    contactLabel: 'सत्यापित संपर्क',
    verifiedBadge: 'सत्यापित',
    termsAgreement: 'मैं सहमत हूँ ',
    termsLink: 'सेवा की शर्तों से',
    privacyLink: 'गोपनीयता नीति',
    submitButton: 'खाता बनाएं',
    signInLabel: 'पहले से ही एक खाता है? ',
    signInLink: 'साइन इन करें'
  },
  kn: {
    brandName: 'ಪ್ರಜಾ ದಿಶಾ',
    leftTitle: 'ನಾಗರಿಕ ಶಕ್ತಿ ನಿಮ್ಮ ಕೈಯಲ್ಲಿದೆ.',
    leftDesc: 'ತಮ್ಮ ಸಮುದಾಯವನ್ನು ಸಕ್ರಿಯವಾಗಿ ರೂಪಿಸುತ್ತಿರುವ ಸಾವಿರಾರು ನಾಗರಿಕರೊಂದಿಗೆ ಸೇರಿಕೊಳ್ಳಿ. ಸಂಪೂರ್ಣ ಪಾರದರ್ಶಕತೆಯೊಂದಿಗೆ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ, ಪರಿಹಾರಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಸ್ಥಳೀಯ ಆಡಳಿತದಲ್ಲಿ ಭಾಗವಹಿಸಿ.',
    rightTitle: 'ಖಾತೆ ರಚಿಸಿ',
    rightSubtitle: 'ಸಾಂಸ್ಥಿಕ ನಾಗರಿಕ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ನೋಂದಾಯಿಸಿ.',
    nameLabel: 'ಪೂರ್ಣ ಹೆಸರು',
    namePlaceholder: 'ಉದಾ: ರಮೇಶ್ ಕುಮಾರ್',
    contactLabel: 'ಪರಿಶೀಲಿಸಿದ ಸಂಪರ್ಕ',
    verifiedBadge: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    termsAgreement: 'ನಾನು ಒಪ್ಪುತ್ತೇನೆ ',
    termsLink: 'ಸೇವಾ ನಿಯಮಗಳು',
    privacyLink: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    submitButton: 'ಖಾತೆ ರಚಿಸಿ',
    signInLabel: 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ? ',
    signInLink: 'ಸೈನ್ ಇನ್ ಮಾಡಿ'
  },
  bn: {
    brandName: 'প্রজা দিশা',
    leftTitle: 'নাগরিক শক্তি আপনার হাতে।',
    leftDesc: 'হাজার হাজার নাগরিকের সাথে যোগ দিন যারা সক্রিয়ভাবে তাদের সম্প্রদায় গঠন করছে। সম্পূর্ণ স্বচ্ছতার সাথে সমস্যাগুলি রিপোর্ট করুন, সমাধানগুলি ট্র্যাক করুন এবং স্থানীয় শাসনে অংশ নিন।',
    rightTitle: 'অ্যাকাউন্ট তৈরি করুন',
    rightSubtitle: 'প্রাতিষ্ঠানিক নাগরিক পরিষেবা অ্যাক্সেস করতে নিবন্ধন করুন।',
    nameLabel: 'সম্পূর্ণ নাম',
    namePlaceholder: 'উদাঃ রাহুল সেন',
    contactLabel: 'যাচাইকৃত যোগাযোগ',
    verifiedBadge: 'যাচাইকৃত',
    termsAgreement: 'আমি সম্মত ',
    termsLink: 'পরিষেবার শর্তাবলী',
    privacyLink: 'গোপনীয়তা নীতি',
    submitButton: 'অ্যাকাউন্ট তৈরি করুন',
    signInLabel: 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে? ',
    signInLink: 'সাইন ইন করুন'
  },
  ta: {
    brandName: 'பிரஜா திஷா',
    leftTitle: 'குடிமை அதிகாரம் உங்கள் கைகளில்.',
    leftDesc: 'தங்கள் சமூகத்தை தீவிரமாக வடிவமைக்கும் ஆயிரக்கணக்கான குடிமக்களுடன் இணையுங்கள். முழுமையான வெளிப்படைத்தன்மையுடன் சிக்கல்களைப் புகாரளிக்கவும், தீர்வுகளைக் கண்காணிக்கவும் மற்றும் உள்ளூர் ஆட்சியில் பங்கேற்கவும்.',
    rightTitle: 'கணக்கை உருவாக்கு',
    rightSubtitle: 'நிறுவன குடிமை சேவைகளை அணுக பதிவு செய்யவும்.',
    nameLabel: 'முழு பெயர்',
    namePlaceholder: 'எ.கா. கார்த்திக்',
    contactLabel: 'சரிபார்க்கப்பட்ட தொடர்பு',
    verifiedBadge: 'சரிபார்க்கப்பட்டது',
    termsAgreement: 'நான் ஒப்புக்கொள்கிறேன் ',
    termsLink: 'சேவை விதிமுறைகள்',
    privacyLink: 'தனியுரிமைக் கொள்கை',
    submitButton: 'கணக்கை உருவாக்கு',
    signInLabel: 'ஏற்கனவே கணக்கு உள்ளதா? ',
    signInLink: 'உள்நுழைக'
  },
  te: {
    brandName: 'ప్రజా దిశ',
    leftTitle: 'పౌర శక్తి మీ చేతుల్లో ఉంది.',
    leftDesc: 'తమ సమాజాన్ని చురుకుగా తీర్చిదిద్దుతున్న వేలాది మంది పౌరులతో చేరండి. సంపూర్ణ పారదర్శకతతో సమస్యలను నివేదించండి, పరిష్కారాలను ట్రాక్ చేయండి మరియు స్థానిక పాలనలో పాల్గొనండి.',
    rightTitle: 'ఖాతాను సృష్టించండి',
    rightSubtitle: 'పౌర సేవలను యాక్సెస్ చేయడానికి నమోదు చేసుకోండి.',
    nameLabel: 'పూర్తి పేరు',
    namePlaceholder: 'ఉదా: కిరణ్ కుమార్',
    contactLabel: 'ధృవీకరించబడిన పరిచయం',
    verifiedBadge: 'ధృవీకరించబడింది',
    termsAgreement: 'నేను అంగీకరిస్తున్నాను ',
    termsLink: 'సేవా నిబంధనలు',
    privacyLink: 'గోప్యతా విధానం',
    submitButton: 'ఖాతాను సృష్టించండి',
    signInLabel: 'ఇప్పటికే ఖాతా ఉందా? ',
    signInLink: 'సైన్ ఇన్'
  },
  mr: {
    brandName: 'प्रजा दिशा',
    leftTitle: 'नागरी शक्ती आपल्या हातात.',
    leftDesc: 'आपल्या समुदायाला सक्रियपणे आकार देणाऱ्या हजारो नागरिकांमध्ये सामील व्हा. पूर्ण पारदर्शकतेसह समस्यांची तक्रार करा, त्यांचे निराकरण ट्रॅक करा आणि स्थानिक प्रशासनात सहभागी व्हा.',
    rightTitle: 'खाते तयार करा',
    rightSubtitle: 'नागरी सेवांमध्ये प्रवेश मिळवण्यासाठी नोंदणी करा.',
    nameLabel: 'पूर्ण नाव',
    namePlaceholder: 'उदा. अमित पाटील',
    contactLabel: 'सत्यापित संपर्क',
    verifiedBadge: 'सत्यापित',
    termsAgreement: 'मी सहमत आहे ',
    termsLink: 'सेवा अटी',
    privacyLink: 'गोपनीयता धोरण',
    submitButton: 'खाते तयार करा',
    signInLabel: 'आधीच खाते आहे? ',
    signInLink: 'साइन इन करा'
  },
  ur: {
    brandName: 'प्रजा दिशा',
    leftTitle: 'شہری طاقت آپ کے ہاتھ میں ہے۔',
    leftDesc: 'ان ہزاروں شہریوں میں شامل ہوں جو اپنے معاشرے کو بہتر بنا رہے ہیں۔ مسائل رپورٹ کریں، ان کے حل پر نظر رکھیں اور بلدیاتی نظم و نسق میں حصہ لیں۔',
    rightTitle: 'اکاؤنٹ بنائیں',
    rightSubtitle: 'بلدیاتی خدمات تک رسائی حاصل کرنے کے لیے رجسٹر کریں۔',
    nameLabel: 'پورا نام',
    namePlaceholder: 'مثال کے طور پر ساجد علی',
    contactLabel: 'تصدیق شدہ رابطہ',
    verifiedBadge: 'تصدیق شدہ',
    termsAgreement: 'میں متفق ہوں ',
    termsLink: 'سروس کی شرائط',
    privacyLink: 'رازداری کی پالیسی',
    submitButton: 'اکاؤنٹ بنائیں',
    signInLabel: 'پہلے سے ہی اکاؤنٹ موجود ہے؟ ',
    signInLink: 'سائن ان کریں'
  },
  gu: {
    brandName: 'પ્રજા દિશા',
    leftTitle: 'નાગરિક શક્તિ તમારા હાથમાં.',
    leftDesc: 'પોતાના સમુદાયને સક્રિય રીતે આકાર આપતા હજારો નાગરિકો સાથે જોડાઓ. સંપૂર્ણ પારદર્શિતા સાથે પ્રશ્નો રિપોર્ટ કરો, ઉકેલ ટ્રેક કરો અને સ્થાનિક વહીવટમાં ભાગ લો.',
    rightTitle: 'ખાતું બનાવો',
    rightSubtitle: 'નાગરિક સેવાઓનો લાભ લેવા માટે નોંધણી કરો.',
    nameLabel: 'પૂરું નામ',
    namePlaceholder: 'દા.ત. નિકુંજ પટેલ',
    contactLabel: 'ચકાસાયેલ સંપર્ક',
    verifiedBadge: 'ચકાસાયેલ',
    termsAgreement: 'હું સહમત છું ',
    termsLink: 'સેવાની શરતો',
    privacyLink: 'ગોપનીયતા નીતિ',
    submitButton: 'ખાતું બનાવો',
    signInLabel: 'પહેલેથી જ ખાતું છે? ',
    signInLink: 'સાઇન ઇન'
  },
  ml: {
    brandName: 'പ്രജാ ദിശ',
    leftTitle: 'പൗരാധികാരം നിങ്ങളുടെ കൈകളിൽ.',
    leftDesc: 'തങ്ങളുടെ പ്രദേശത്തെ കൂടുതൽ മെച്ചപ്പെടുത്താൻ പ്രവർത്തിക്കുന്ന ആയിരക്കണക്കിന് പൗരന്മാർക്കൊപ്പം ചേരുക. പ്രശ്നങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക, പുരോഗതി നിരീക്ഷിക്കുക.',
    rightTitle: 'അക്കൗണ്ട് നിർമ്മിക്കുക',
    rightSubtitle: 'ഔദ്യോഗിക പൗരസേവനങ്ങൾ പ്രയോജനപ്പെടുത്താൻ രജിസ്റ്റർ ചെയ്യുക.',
    nameLabel: 'പൂർണ്ണ നാമം',
    namePlaceholder: 'ഉദാ: അരുൺ കൃഷ്ണൻ',
    contactLabel: 'സ്ഥിരീകരിച്ച ബന്ധപ്പെടൽ വിവരം',
    verifiedBadge: 'സ്ഥിരീകരിച്ചു',
    termsAgreement: 'ഞാൻ യോജിക്കുന്നു ',
    termsLink: 'സേവന വ്യവസ്ഥകൾ',
    privacyLink: 'സ്വകാര്യതാ നയം',
    submitButton: 'അക്കൗണ്ട് നിർമ്മിക്കുക',
    signInLabel: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ? ',
    signInLink: 'സൈൻ ഇൻ ചെയ്യുക'
  },
  pa: {
    brandName: 'ਪ੍ਰਜਾ ਦਿਸ਼ਾ',
    leftTitle: 'ਨਾਗਰਿਕ ਸ਼ਕਤੀ ਤੁਹਾਡੇ ਹੱਥਾਂ ਵਿੱਚ।',
    leftDesc: 'ਆਪਣੇ ਭਾਈਚਾਰੇ ਨੂੰ ਸਰਗਰਮੀ ਨਾਲ ਨਵਾਂ ਰੂਪ ਦੇ ਰਹੇ ਹਜ਼ਾਰਾਂ ਨਾਗਰਿਕਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ। ਪੂਰੀ ਪਾਰਦਰਸ਼ਤਾ ਨਾਲ ਸਮੱਸਿਆਵਾਂ ਦੀ ਰਿਪੋਰਟ ਕਰੋ।',
    rightTitle: 'ਖਾਤਾ ਬਣਾਓ',
    rightSubtitle: 'ਨਾਗਰਿਕ ਸੇਵਾਵਾਂ ਤੱਕ ਪਹੁੰਚ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਰਜਿਸਟਰ ਕਰੋ।',
    nameLabel: 'ਪੂਰਾ ਨਾਮ',
    namePlaceholder: 'ਉਦਾਹਰਨ: ਹਰਪ੍ਰੀਤ ਸਿੰਘ',
    contactLabel: 'ਪ੍ਰਮਾਣਿਤ ਸੰਪਰਕ',
    verifiedBadge: 'ਪ੍ਰਮਾਣਿਤ',
    termsAgreement: 'ਮੈਂ ਸਹਿਮਤ ਹਾਂ ',
    termsLink: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ ਨਾਲ',
    privacyLink: 'ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ',
    submitButton: 'ਖਾਤਾ ਬਣਾਓ',
    signInLabel: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ? ',
    signInLink: 'ਸਾਈਨ ਇਨ ਕਰੋ'
  },
  or: {
    brandName: 'ପ୍ରଜା ଦିଶା',
    leftTitle: 'ନାଗରିକ ଶକ୍ତି ଆପଣଙ୍କ ହାତରେ।',
    leftDesc: 'ଆପଣଙ୍କ ସମ୍ପ୍ରଦାୟକୁ ଗଠନ କରୁଥିବା ହଜାର ହଜାର ନାଗରିକଙ୍କ ସହ ଯୋଡି ହୁଅନ୍ତୁ। ସମ୍ପୂର୍ଣ୍ଣ ସ୍ୱଚ୍ଛତା ସହ ସମସ୍ୟାର ରିପୋର୍ଟ କରନ୍ତୁ।',
    rightTitle: 'ଖାତା ଖୋଲନ୍ତୁ',
    rightSubtitle: 'ନାଗରିକ ସେବାଗୁଡିକୁ ଉପଯୋଗ କରିବା ପାଇଁ ପଞ୍ଜୀକରଣ କରନ୍ତୁ।',
    nameLabel: 'ପୂରା ନାମ',
    namePlaceholder: 'ଉଦାହରଣ: ପ୍ରିୟଙ୍କା ଦାସ',
    contactLabel: 'ଯାଞ୍ଚ ହୋଇଥିବା ଯୋଗାଯୋଗ',
    verifiedBadge: 'ଯାଞ୍ଚ ହୋଇଛି',
    termsAgreement: 'ମୁଁ ସହମତ ',
    termsLink: 'ସେବା ସର୍ତ୍ତାବଳୀ',
    privacyLink: 'ଗୋପନୀୟତା ନୀତି',
    submitButton: 'ଖାତା ଖୋଲନ୍ତୁ',
    signInLabel: 'ପୂର୍ବରୁ ଖାତା ଅଛି କି? ',
    signInLink: 'ସାଇନ ଇନ'
  },
  as: {
    brandName: 'প্ৰজা দিশা',
    leftTitle: 'নাগৰিক শক্তি আপোনাৰ হাতত।',
    leftDesc: 'সহস্ৰ নাগৰিকৰ সৈতে যোগ দি নিজৰ সমাজখন উন্নত কৰক। সম্পূৰ্ণ স্বচ্ছতাৰে সমস্যাৰ অভিযোগ দাখিল কৰক।',
    rightTitle: 'একাউণ্ট খোলক',
    rightSubtitle: 'প্ৰতিষ্ঠানিক নাগৰিক সেৱাসমূহ ব্যৱহাৰ কৰিবলৈ পঞ্জীয়ন কৰক।',
    nameLabel: 'সম্পূৰ্ণ নাম',
    namePlaceholder: 'যেনে: জয়ন্ত বৰুৱা',
    contactLabel: 'প্ৰমাণিত যোগাযোগ',
    verifiedBadge: 'প্ৰমাণিত',
    termsAgreement: 'মই সন্মত ',
    termsLink: 'সেৱাৰ চৰ্তাৱলী',
    privacyLink: 'গোপনীয়তা নীতি',
    submitButton: 'একাউণ্ট খোলক',
    signInLabel: 'ইতিমধ্যে একাউণ্ট আছে নেকি? ',
    signInLink: 'ছাইন ইন কৰক'
  }
};
