/** GeoJSON Point used for geospatial indexing of task location */
export interface GeoPoint {
  type: 'Point';
  coordinates: [number, number]; // [Longitude, Latitude]
}

/** Physical location of the reported issue */
export interface TaskLocation {
  address: string;
  geo: GeoPoint;
}

/** Core task / ticket submitted by a citizen */
export interface Task {
  id: string;                   // MongoDB ObjectId as string
  groupId: string;              // Duplicate tickets share the same groupId
  parentTaskId: string | null;  // Non-null for sub-tasks
  orgId: string;
  citizenUserName: string;
  title: string;                // Auto-generated by AI
  description: string;          // Merged voice transcription or raw text
  voiceUrl: string;             // Path to stored voice file if provided
  imageUrl: string;             // Path or Base64 encoded snapshot string
  language: string;
  location: TaskLocation;
  category: string;
  priority: string;
  globalStatus: string;         // Overall ticket lifecycle state (e.g. "OPEN", "RESOLVED")
  isReviewed: boolean;          // False on auto-assign; true once verified/modified by officer
  dueDate: number;              // Unix timestamp (milliseconds)
  createdAt: number;
  descriptionEmbedding: number[]; // Vector embedding generated by Ollama
}
