const en = {
  title: 'Report Issue',
  subtitle: 'Submit a civic concern in seconds. Use your voice or camera for speed.',
  textareaLabel: 'Describe the issue',
  textareaPlaceholder: 'Describe what\'s happening... (e.g., Pothole on Maple St, broken street light, etc.)',
  textareaHint: 'Type or tap the mic to speak.',
  micListening: 'Listening...',
  micTapToSpeak: 'Tap to Speak',
  locationLabel: 'Location Verification',
  locationPlaceholder: 'Enter address manually or detect',
  locationDetectBtn: 'Detect My Location',
  detectingLocation: 'Detecting...',
  uploadLabel: 'Upload Image Proof',
  uploadDesc: 'Photos help our teams prioritize and resolve issues faster.',
  uploadHint: 'Max 5 images or videos',
  submitBtn: 'Submit Ticket',
  submittingBtn: 'Submitting...',
  successNotification: 'Ticket submitted successfully!'
};

export const REPORT_STRINGS: Record<string, typeof en> = {
  en,
  hi: {
    title: 'समस्या की रिपोर्ट करें',
    subtitle: 'सेकंडों में नागरिक चिंता दर्ज करें। गति के लिए अपनी आवाज़ या कैमरे का उपयोग करें।',
    textareaLabel: 'समस्या का वर्णन करें',
    textareaPlaceholder: 'वर्णन करें कि क्या हो रहा है... (जैसे, मुख्य सड़क पर गड्ढा, टूटी स्ट्रीट लाइट, आदि)',
    textareaHint: 'बोलने के लिए टाइप करें या माइक पर टैप करें।',
    micListening: 'सुन रहा है...',
    micTapToSpeak: 'बोलने के लिए टैप करें',
    locationLabel: 'स्थान सत्यापन',
    locationPlaceholder: 'पता मैन्युअल रूप से दर्ज करें या पता लगाएं',
    locationDetectBtn: 'मेरा स्थान ढूंढें',
    detectingLocation: 'पता लगा रहा है...',
    uploadLabel: 'छवि प्रमाण अपलोड करें',
    uploadDesc: 'तस्वीरें हमारी टीमों को प्राथमिकताओं को तय करने और समस्याओं को तेज़ी से हल करने में मदद करती हैं।',
    uploadHint: 'अधिकतम 5 चित्र या वीडियो',
    submitBtn: 'टिकट जमा करें',
    submittingBtn: 'जमा किया जा रहा है...',
    successNotification: 'टिकट सफलतापूर्वक जमा किया गया!'
  },
  kn: {
    title: 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    subtitle: 'ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ನಾಗರಿಕ ಕಾಳಜಿಯನ್ನು ಸಲ್ಲಿಸಿ. ವೇಗಕ್ಕಾಗಿ ನಿಮ್ಮ ಧ್ವನಿ ಅಥವಾ ಕ್ಯಾಮೆರಾ ಬಳಸಿ.',
    textareaLabel: 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',
    textareaPlaceholder: 'ಏನಾಗುತ್ತಿದೆ ಎಂದು ವಿವರಿಸಿ... (ಉದಾಹರಣೆಗೆ, ರಸ್ತೆಯಲ್ಲಿ ಗುಂಡಿ, ಒಡೆದ ಬೀದಿ ದೀಪ, ಇತ್ಯಾದಿ)',
    textareaHint: 'ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮಾತನಾಡಲು ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ.',
    micListening: 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...',
    micTapToSpeak: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    locationLabel: 'ಸ್ಥಳ ಪರಿಶೀಲನೆ',
    locationPlaceholder: 'ವಿಳಾಸವನ್ನು ಹಸ್ತಚಾಲಿತವಾಗಿ ನಮೂದಿಸಿ ಅಥವಾ ಪತ್ತೆ ಮಾಡಿ',
    locationDetectBtn: 'ನನ್ನ ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಿ',
    detectingLocation: 'ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    uploadLabel: 'ಚಿತ್ರದ ಪುರಾವೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    uploadDesc: 'ಚಿತ್ರಗಳು ನಮ್ಮ ತಂಡಗಳಿಗೆ ಆದ್ಯತೆ ನೀಡಲು ಮತ್ತು ಸಮಸ್ಯೆಗಳನ್ನು ವೇಗವಾಗಿ ಪರಿಹರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    uploadHint: 'ಗರಿಷ್ಠ 5 ಚಿತ್ರಗಳು ಅಥವಾ ವೀಡಿಯೊಗಳು',
    submitBtn: 'ಟಿಕೆಟ್ ಸಲ್ಲಿಸಿ',
    submittingBtn: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    successNotification: 'ಟಿಕೆಟ್ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಕೆಯಾಗಿದೆ!'
  },
  bn: {
    title: 'সমস্যা রিপোর্ট করুন',
    subtitle: 'কয়েক সেকেন্ডের মধ্যে নাগরিক উদ্বেগ জমা দিন। গতি বাড়ানোর জন্য আপনার ভয়েস বা ক্যামেরা ব্যবহার করুন।',
    textareaLabel: 'সমস্যাটি বর্ণনা করুন',
    textareaPlaceholder: 'কী ঘটছে তা বর্ণনা করুন... (যেমন, রাস্তায় গর্ত, ভাঙা রাস্তার আলো ইত্যাদি)',
    textareaHint: 'টাইপ করুন বা কথা বলার জন্য মাইকে চাপ দিন।',
    micListening: 'শুনছে...',
    micTapToSpeak: 'কথা বলতে চাপ দিন',
    locationLabel: 'অবস্থান যাচাইকরণ',
    locationPlaceholder: 'ম্যানুয়ালি ঠিকানা লিখুন বা সনাক্ত করুন',
    locationDetectBtn: 'আমার অবস্থান সনাক্ত করুন',
    detectingLocation: 'সনাক্ত করা হচ্ছে...',
    uploadLabel: 'ছবির প্রমাণ আপলোড করুন',
    uploadDesc: 'ছবিগুলি আমাদের দলগুলিকে অগ্রাধিকার দিতে এবং সমস্যাগুলি দ্রুত সমাধান করতে সহায়তা করে।',
    uploadHint: 'সর্বোচ্চ ৫টি ছবি বা ভিডিও',
    submitBtn: 'টিকিট জমা দিন',
    submittingBtn: 'জমা হচ্ছে...',
    successNotification: 'টিকিট সফলভাবে জমা হয়েছে!'
  },
  ta: {
    title: 'பிரச்சினையைப் புகாரளி',
    subtitle: 'சில நொடிகளில் குடிமைப் புகாரைச் சமர்ப்பிக்கவும். வேகத்திற்கு உங்கள் குரல் அல்லது கேமராவைப் பயன்படுத்தவும்.',
    textareaLabel: 'பிரச்சினையை விவரிக்கவும்',
    textareaPlaceholder: 'என்ன நடக்கிறது என்பதை விவரிக்கவும்... (எ.கா. சாலையில் குழி, உடைந்த தெருவிளக்கு போன்றவை)',
    textareaHint: 'தட்டச்சு செய்யவும் அல்லது பேச மைக் மீது தட்டவும்.',
    micListening: 'கேட்கிறது...',
    micTapToSpeak: 'பேச தட்டவும்',
    locationLabel: 'இருப்பிட சரிபார்ப்பு',
    locationPlaceholder: 'முகவரியை கைமுறையாக உள்ளிடவும் அல்லது கண்டறியவும்',
    locationDetectBtn: 'எனது இருப்பிடத்தைக் கண்டறி',
    detectingLocation: 'கண்டறியப்படுகிறது...',
    uploadLabel: 'புகைப்பட ஆதாரத்தைப் பதிவேற்றவும்',
    uploadDesc: 'புகைப்படங்கள் எங்கள் குழுக்களுக்கு முன்னுரிமை அளிக்கவும் சிக்கல்களை விரைவாக தீர்க்கவும் உதவுகின்றன.',
    uploadHint: 'அதிகபட்சம் 5 படங்கள் அல்லது வீடியோக்கள்',
    submitBtn: 'புகாரைச் சமர்ப்பி',
    submittingBtn: 'சமர்ப்பிக்கப்படுகிறது...',
    successNotification: 'புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!'
  },
  te: {
    title: 'సమస్యను నివేదించండి',
    subtitle: 'సెకన్లలో పౌర ఆందోళనను సమర్పించండి. వేగం కోసం మీ వాయిస్ లేదా కెమెరాను ఉపయోగించండి.',
    textareaLabel: 'సమస్యను వివరించండి',
    textareaPlaceholder: 'ఏం జరుగుతుందో వివరించండి... (ఉదా: రోడ్డుపై గుంత, విరిగిన వీధి దీపం, మొదలైనవి)',
    textareaHint: 'టైప్ చేయండి లేదా మాట్లాడటానికి మైక్ నొక్కండి.',
    micListening: 'వింటోంది...',
    micTapToSpeak: 'మాట్లాడటానికి నొక్కండి',
    locationLabel: 'స్థాన ధృవీకరణ',
    locationPlaceholder: 'చిరునామాను మాన్యువల్‌గా నమోదు చేయండి లేదా గుర్తించండి',
    locationDetectBtn: 'నా స్థానాన్ని గుర్తించు',
    detectingLocation: 'గుర్తిస్తోంది...',
    uploadLabel: 'చిత్ర ఆధారాన్ని అప్‌లోడ్ చేయండి',
    uploadDesc: 'చిత్రాలు మా బృందాలకు సమస్యలను త్వరగా పరిష్కరించడానికి సహాయపడతాయి.',
    uploadHint: 'గరిష్టంగా 5 చిత్రాలు లేదా వీడియోలు',
    submitBtn: 'టికెట్ సమర్పించండి',
    submittingBtn: 'సమర్పిస్తోంది...',
    successNotification: 'టికెట్ విజయవంతంగా సమర్పించబడింది!'
  },
  mr: {
    title: 'समस्येची तक्रार करा',
    subtitle: 'काही सेकंदात नागरी चिंता सबमिट करा. वेगासाठी आपला आवाज किंवा कॅमेरा वापरा.',
    textareaLabel: 'समस्येचे वर्णन करा',
    textareaPlaceholder: 'काय घडत आहे याचे वर्णन करा... (उदा. रस्त्यावरील खड्डा, नादुरुस्त पथदिवा, इ.)',
    textareaHint: 'टाईप करा किंवा बोलण्यासाठी माईकवर टॅप करा.',
    micListening: 'ऐकत आहे...',
    micTapToSpeak: 'बोलण्यासाठी टॅप करा',
    locationLabel: 'स्थान पडताळणी',
    locationPlaceholder: 'पत्ता मॅन्युअली प्रविष्ट करा किंवा शोधा',
    locationDetectBtn: 'माझे स्थान शोधा',
    detectingLocation: 'शोधत आहे...',
    uploadLabel: 'फोटो पुरावा अपलोड करा',
    uploadDesc: 'फोटोंमुळे आमच्या टीमना प्राधान्य देण्यास आणि समस्या जलद सोडविण्यास मदत होते.',
    uploadHint: 'कमाल ५ चित्रे किंवा व्हिडिओ',
    submitBtn: 'तिकीट सबमिट करा',
    submittingBtn: 'सबमिट होत आहे...',
    successNotification: 'तिकीट यशस्वीरित्या सबमिट झाले!'
  },
  ur: {
    title: 'مسئلہ رپورٹ کریں',
    subtitle: 'سیکنڈوں میں شہری مسئلہ جمع کریں۔ تیزی کے لیے اپنی آواز یا کیمرے کا استعمال کریں۔',
    textareaLabel: 'مسئلے کی وضاحت کریں',
    textareaPlaceholder: 'وضاحت کریں کہ کیا ہو رہا ہے... (مثلاً سڑک پر گڑھا، ٹوٹی ہوئی اسٹریٹ لائٹ وغیرہ)',
    textareaHint: 'ٹائپ کریں یا بولنے کے لیے مائیک دبائیں۔',
    micListening: 'سن رہا ہے...',
    micTapToSpeak: 'بولنے کے لیے دبائیں',
    locationLabel: 'مقام کی تصدیق',
    locationPlaceholder: 'پتہ خود درج کریں یا تلاش کریں',
    locationDetectBtn: 'میرا مقام تلاش کریں',
    detectingLocation: 'تلاش کر رہا ہے...',
    uploadLabel: 'تصویری ثبوت اپ لوڈ کریں',
    uploadDesc: 'تصاویر ہماری ٹیموں کو ترجیحات طے کرنے اور مسائل کو تیزی سے حل کرنے میں مدد کرتی ہیں۔',
    uploadHint: 'زیادہ سے زیادہ 5 تصاویر یا ویڈیوز',
    submitBtn: 'ٹکٹ جمع کروائیں',
    submittingBtn: 'جمع ہو رہا ہے...',
    successNotification: 'ٹکٹ کامیابی سے جمع ہو گیا!'
  },
  gu: {
    title: 'સમસ્યા રિપોર્ટ કરો',
    subtitle: 'સેકન્ડોમાં નાગરિક ચિંતા સબમિટ કરો. ગતિ માટે તમારા અવાજ અથવા કેમેરાનો ઉપયોગ કરો.',
    textareaLabel: 'સમસ્યાનું વર્ણન કરો',
    textareaPlaceholder: 'શું થઈ રહ્યું છે તેનું વર્ણન કરો... (દા.ત. રસ્તા પર ખાડો, તૂટેલી સ્ટ્રીટ લાઈટ વગેરે)',
    textareaHint: 'ટાઈપ કરો અથવા બોલવા માટે માઈક ટેપ કરો.',
    micListening: 'સાંભળી રહ્યું છે...',
    micTapToSpeak: 'બોલવા માટે ટેપ કરો',
    locationLabel: 'સ્થાન ચકાસણી',
    locationPlaceholder: 'સરનામું જાતે દાખલ કરો અથવા શોધો',
    locationDetectBtn: 'મારું સ્થાન શોધો',
    detectingLocation: 'શોધી રહ્યું છે...',
    uploadLabel: 'ફોટો પુરાવો અપલોડ કરો',
    uploadDesc: 'ફોટા અમારી ટીમોને પ્રાથમિકતા આપવા અને સમસ્યાઓ ઝડપથી ઉકેલવામાં મદદ કરે છે.',
    uploadHint: 'મહત્તમ 5 છબીઓ અથવા વિડિઓઝ',
    submitBtn: 'ટિકિટ સબમિટ કરો',
    submittingBtn: 'સબમિટ થઈ રહ્યું છે...',
    successNotification: 'ટિકિટ સફળતાપૂર્વક સબમિટ થઈ ગઈ!'
  },
  ml: {
    title: 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',
    subtitle: 'നിമിഷങ്ങൾക്കുള്ളിൽ സിവിക് പരാതി സമർപ്പിക്കുക. വേഗതയ്ക്കായി ശബ്ദമോ ക്യാമറയോ ഉപയോഗിക്കുക.',
    textareaLabel: 'പ്രശ്നം വിവരിക്കുക',
    textareaPlaceholder: 'എന്താണ് സംഭവിക്കുന്നതെന്ന് വിവരിക്കുക... (ഉദാ: റോഡിലെ കുഴി, തെരുവ് വിളക്ക് കേടായത്)',
    textareaHint: 'ടൈപ്പ് ചെയ്യുക അല്ലെങ്കിൽ സംസാരിക്കാൻ മൈക്ക് അമർത്തുക.',
    micListening: 'ശ്രദ്ധിക്കുന്നു...',
    micTapToSpeak: 'സംസാരിക്കാൻ അമർത്തുക',
    locationLabel: 'ലൊക്കേഷൻ സ്ഥിരീകരണം',
    locationPlaceholder: 'വിലാസം നേരിട്ട് നൽകുക അല്ലെങ്കിൽ കണ്ടെത്തുക',
    locationDetectBtn: 'എന്റെ ലൊക്കേഷൻ കണ്ടെത്തുക',
    detectingLocation: 'കണ്ടെത്തുന്നു...',
    uploadLabel: 'ചിത്ര തെളിവ് അപ്‌ലോഡ് ചെയ്യുക',
    uploadDesc: 'ചിത്രങ്ങൾ പ്രശ്നം വേഗത്തിൽ പരിഹരിക്കാൻ ഞങ്ങളുടെ ടീമുകളെ സഹായിക്കുന്നു.',
    uploadHint: 'പരമാവധി 5 ചിത്രങ്ങൾ അല്ലെങ്കിൽ വീഡിയോകൾ',
    submitBtn: 'ടിക്കറ്റ് സമർപ്പിക്കുക',
    submittingBtn: 'സമർപ്പിക്കുന്നു...',
    successNotification: 'ടിക്കറ്റ് വിജയകരമായി സമർപ്പിച്ചു!'
  },
  pa: {
    title: 'ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    subtitle: 'ਸਕਿੰਟਾਂ ਵਿੱਚ ਨਾਗਰਿਕ ਚਿੰਤਾ ਦਰਜ ਕਰੋ। ਤੇਜ਼ੀ ਲਈ ਆਪਣੀ ਆਵਾਜ਼ ਜਾਂ ਕੈਮਰੇ ਦੀ ਵਰਤੋਂ ਕਰੋ।',
    textareaLabel: 'ਸਮੱਸਿਆ ਦਾ ਵਰਣਨ ਕਰੋ',
    textareaPlaceholder: 'ਦੱਸੋ ਕੀ ਹੋ ਰਿਹਾ ਹੈ... (ਜਿਵੇਂ ਕਿ ਸੜਕ ਵਿੱਚ ਟੋਆ, ਟੁੱਟੀ ਸਟ੍ਰੀਟ ਲਾਈਟ, ਆਦਿ)',
    textareaHint: 'ਟਾਈਪ ਕਰੋ ਜਾਂ ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ।',
    micListening: 'ਸੁਣ ਰਿਹਾ ਹੈ...',
    micTapToSpeak: 'ਬੋਲਣ ਲਈ ਦਬਾਓ',
    locationLabel: 'ਸਥਾਨ ਦੀ ਪੁਸ਼ਟੀ',
    locationPlaceholder: 'ਪਤਾ ਖੁਦ ਦਰਜ ਕਰੋ ਜਾਂ ਖੋਜੋ',
    locationDetectBtn: 'ਮੇਰੀ ਲੋਕੇਸ਼ਨ ਲੱਭੋ',
    detectingLocation: 'ਲੱਭ ਰਿਹਾ ਹੈ...',
    uploadLabel: 'ਤਸਵੀਰ ਦਾ ਸਬੂਤ ਅਪਲੋਡ ਕਰੋ',
    uploadDesc: 'ਤਸਵੀਰਾਂ ਸਾਡੀ ਟੀਮ ਨੂੰ ਸਮੱਸਿਆਵਾਂ ਜਲਦੀ ਹੱਲ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦੀਆਂ ਹਨ।',
    uploadHint: 'ਵੱਧ ਤੋਂ ਵੱਧ 5 ਤਸਵੀਰਾਂ ਜਾਂ ਵੀਡੀਓ',
    submitBtn: 'ਟਿਕਟ ਜਮ੍ਹਾਂ ਕਰੋ',
    submittingBtn: 'ਜਮ੍ਹਾਂ ਹੋ ਰਿਹਾ ਹੈ...',
    successNotification: 'ਟਿਕਟ ਸਫ਼ਲਤਾਪੂਰਵਕ ਜਮ੍ਹਾਂ ਹੋ ਗਈ ਹੈ!'
  },
  or: {
    title: 'ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ',
    subtitle: 'ସେକେଣ୍ଡ ମଧ୍ୟରେ ସମସ୍ୟା ଦାଖଲ କରନ୍ତୁ। ଦ୍ରୁତ କାର୍ଯ୍ୟ ପାଇଁ ଆପଣଙ୍କ ସ୍ୱର କିମ୍ବା କ୍ୟାମେରା ବ୍ୟବହାର କରନ୍ତୁ।',
    textareaLabel: 'ସମସ୍ୟାର ବର୍ଣ୍ଣନା କରନ୍ତୁ',
    textareaPlaceholder: 'କଣ ହେଉଛି ବର୍ଣ୍ଣନା କରନ୍ତୁ... (ଯେମିତିକି ରାସ୍ତାରେ ଖାଲ, ଲାଇଟ୍ ଖରାପ ଇତ୍ୟାଦି)',
    textareaHint: 'ଟାଇପ୍ କରନ୍ତୁ କିମ୍ବା କହିବା ପାଇଁ ମାଇକ୍ ଦବାନ୍ତୁ।',
    micListening: 'ଶୁଣୁଛି...',
    micTapToSpeak: 'କହିବା ପାଇଁ ଦବାନ୍ତୁ',
    locationLabel: 'ସ୍ଥାନ ଯାଞ୍ଚ',
    locationPlaceholder: 'ଠିକଣା ନିଜେ ଲେଖନ୍ତୁ କିମ୍ବା ସନ୍ଧାନ କରନ୍ତୁ',
    locationDetectBtn: 'ମୋର ସ୍ଥାନ ଖୋଜନ୍ତୁ',
    detectingLocation: 'ଖୋଜୁଛି...',
    uploadLabel: 'ଛବି ପ୍ରମାଣ ଅପଲୋଡ୍ କରନ୍ତୁ',
    uploadDesc: 'ଛବିଗୁଡିକ ଆମ ଦଳକୁ ସମସ୍ୟାର ସମାଧାନ ଶୀଘ୍ର କରିବାରେ ସାହାଯ្យ କରେ।',
    uploadHint: 'ସର୍ବାଧିକ ୫ଟି ଛବି କିମ୍ବା ଭିଡିଓ',
    submitBtn: 'ଟିକେଟ୍ ଦାଖଲ କରନ୍ତୁ',
    submittingBtn: 'ଦାଖଲ ହେଉଛି...',
    successNotification: 'ଟିକେଟ୍ ସଫଳତାର ସହ ଦାଖଲ ହେଲା!'
  },
  as: {
    title: 'অভিযোগ দাখিল কৰক',
    subtitle: 'নাগৰিকৰ সমস্যা কেই চেকেণ্ডমানতে দাখিল কৰক। সহায়ৰ বাবে আপোনাৰ মাত বা কেমেৰা ব্যৱহাৰ কৰক।',
    textareaLabel: 'সমস্যাটো বৰ্ণনা কৰক',
    textareaPlaceholder: 'কি হৈছে বৰ্ণনা কৰক... (যেনে: পথৰ খালা, বেয়া বাটৰ লাইট ইত্যাদি)',
    textareaHint: 'টাইপ কৰক বা কথা কবলৈ মাইকত টিপক।',
    micListening: 'শুনি থকা হৈছে...',
    micTapToSpeak: 'কথা কবলৈ টিপক',
    locationLabel: 'স্থান পৰীক্ষণ',
    locationPlaceholder: 'ঠিকনা নিজেই লিখক বা সন্ধান কৰক',
    locationDetectBtn: 'মোৰ স্থান উলিয়াওক',
    detectingLocation: 'বিচাৰি থকা হৈছে...',
    uploadLabel: 'ছবিৰ প্ৰমাণ আপলোড কৰক',
    uploadDesc: 'ছবিসমূহে আমাৰ দলক সমস্যাৰ সোনকালে সমাধান কৰাত সহায় কৰে।',
    uploadHint: 'সৰ্বাধিক ৫খন ছবি বা ভিডিঅ’',
    submitBtn: 'টিকট দাখিল কৰক',
    submittingBtn: 'দাখিল কৰি থকা হৈছে...',
    successNotification: 'টিকট সফলতাৰে দাখিল কৰা হৈছে!'
  }
};
